// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review.Domain;

#nullable disable

namespace Review.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240529123647_Initialization")]
    partial class Initialization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Review.Domain.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2937f7c4-de05-4761-8d48-997fca5db7ba"),
                            CreateDate = new DateTime(2024, 3, 8, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3866),
                            Grade = 2,
                            ProductId = new Guid("402712e1-1881-4dda-9938-609d104a3ff1"),
                            Rating = 3.3799999999999999,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s",
                            UserId = new Guid("d4bae24a-7768-4c47-b075-2708e84f7974")
                        },
                        new
                        {
                            Id = new Guid("c20ac6ec-204f-40ff-935e-5cbd3f0600a8"),
                            CreateDate = new DateTime(2024, 2, 24, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3879),
                            Grade = 4,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing eli",
                            UserId = new Guid("cd6e1d12-c998-4b9f-b785-866e19c29995")
                        },
                        new
                        {
                            Id = new Guid("ad32188c-3ac0-41f2-ae86-41c0089babcf"),
                            CreateDate = new DateTime(2024, 4, 17, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3919),
                            Grade = 4,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = new Guid("adff3126-9380-4d22-98ae-09274246e66c")
                        },
                        new
                        {
                            Id = new Guid("17c22516-4690-4b10-9393-b38e4a5a5d43"),
                            CreateDate = new DateTime(2024, 5, 7, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3926),
                            Grade = 2,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut l",
                            UserId = new Guid("c3bf4413-62ab-4bc9-966a-ca314e53e072")
                        },
                        new
                        {
                            Id = new Guid("0db6446c-a785-493c-818d-46c970f94afd"),
                            CreateDate = new DateTime(2024, 3, 10, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3929),
                            Grade = 1,
                            ProductId = new Guid("a8b6cdb9-0c82-4939-b593-4eca6ca684cf"),
                            Rating = 2.4399999999999999,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut",
                            UserId = new Guid("80494bde-b06d-4933-a7bb-00d810512d3e")
                        },
                        new
                        {
                            Id = new Guid("29a7d5ca-cecc-4bba-beb7-b6becf355e83"),
                            CreateDate = new DateTime(2024, 5, 22, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3932),
                            Grade = 2,
                            ProductId = new Guid("402712e1-1881-4dda-9938-609d104a3ff1"),
                            Rating = 3.3799999999999999,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, ",
                            UserId = new Guid("4bd0ad41-b0d2-4227-a045-82feb408baeb")
                        },
                        new
                        {
                            Id = new Guid("46459d72-1d9c-42f6-b354-2be0dbdf9f0a"),
                            CreateDate = new DateTime(2024, 3, 2, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3939),
                            Grade = 4,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci",
                            UserId = new Guid("aef3864c-027d-45fb-848e-05cd70859c08")
                        },
                        new
                        {
                            Id = new Guid("f1b85468-b632-4855-ac1f-43de57d7d679"),
                            CreateDate = new DateTime(2024, 3, 12, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3942),
                            Grade = 2,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = new Guid("27d6c31d-21f7-49ea-8aee-a47f31a7ab5f")
                        },
                        new
                        {
                            Id = new Guid("fc932c6a-97f0-4bef-9e81-43c4089a0a26"),
                            CreateDate = new DateTime(2024, 3, 24, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3945),
                            Grade = 1,
                            ProductId = new Guid("218bde1c-db2a-4da7-9115-3e5829d8a237"),
                            Rating = 2.71,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adip",
                            UserId = new Guid("d678aead-daf7-4d2e-864a-17a24541e238")
                        },
                        new
                        {
                            Id = new Guid("281f103b-a147-4621-8ba7-856a9d82e560"),
                            CreateDate = new DateTime(2024, 3, 1, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3948),
                            Grade = 1,
                            ProductId = new Guid("a8b6cdb9-0c82-4939-b593-4eca6ca684cf"),
                            Rating = 2.4399999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labo",
                            UserId = new Guid("96b4f956-b9f2-46e5-99b4-7ee2a9563610")
                        },
                        new
                        {
                            Id = new Guid("c50eee66-60e3-453e-86b9-c4493ba4c3da"),
                            CreateDate = new DateTime(2024, 3, 8, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3954),
                            Grade = 2,
                            ProductId = new Guid("e7f62158-1a40-475b-8e08-0f41423f50ea"),
                            Rating = 2.9100000000000001,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo",
                            UserId = new Guid("cc79e441-afd0-47da-bd44-c4d96783dc3b")
                        },
                        new
                        {
                            Id = new Guid("53c58a6c-0a63-42c4-aecb-c9559472b166"),
                            CreateDate = new DateTime(2024, 5, 7, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3958),
                            Grade = 4,
                            ProductId = new Guid("e7f62158-1a40-475b-8e08-0f41423f50ea"),
                            Rating = 2.9100000000000001,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, con",
                            UserId = new Guid("a3da30a7-f174-4717-aa59-d69f6c528d90")
                        },
                        new
                        {
                            Id = new Guid("4a420661-ce67-4441-83e2-2f5efc88df97"),
                            CreateDate = new DateTime(2024, 3, 5, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3962),
                            Grade = 5,
                            ProductId = new Guid("9c1c98c2-2d02-4895-a94e-e87af4799012"),
                            Rating = 3.3300000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = new Guid("af697a98-f4b2-43c4-a216-87da0de6cb28")
                        },
                        new
                        {
                            Id = new Guid("7ac87743-427f-4ce3-ae20-202d073e4501"),
                            CreateDate = new DateTime(2024, 3, 18, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3965),
                            Grade = 1,
                            ProductId = new Guid("2c9b6dff-e103-4cd5-99c5-0ae5a824197a"),
                            Rating = 2.3300000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo",
                            UserId = new Guid("8130b49c-e4c6-4491-b814-3875b5c0a682")
                        },
                        new
                        {
                            Id = new Guid("70139f1d-ff4e-4eb7-818e-f6e41bdb51fa"),
                            CreateDate = new DateTime(2024, 5, 7, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3971),
                            Grade = 2,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do",
                            UserId = new Guid("a11e38f6-a999-41a1-a29c-9e769bec3f57")
                        },
                        new
                        {
                            Id = new Guid("7fd155a0-5985-49c5-88ee-ed1f41cfbd33"),
                            CreateDate = new DateTime(2024, 4, 5, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3974),
                            Grade = 2,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = new Guid("5d0cfe09-1ef7-4578-baa4-94d30be63f65")
                        },
                        new
                        {
                            Id = new Guid("ceb1965f-d8f7-4d83-914b-a7b5df8890fb"),
                            CreateDate = new DateTime(2024, 3, 14, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3980),
                            Grade = 4,
                            ProductId = new Guid("2c9b6dff-e103-4cd5-99c5-0ae5a824197a"),
                            Rating = 2.3300000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = new Guid("8edf5127-0c12-469b-82d0-39f6cdd9f63e")
                        },
                        new
                        {
                            Id = new Guid("23bf5d2b-da50-4bfb-a61b-65fbc15ff76f"),
                            CreateDate = new DateTime(2024, 3, 25, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3985),
                            Grade = 5,
                            ProductId = new Guid("9c1c98c2-2d02-4895-a94e-e87af4799012"),
                            Rating = 3.3300000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = new Guid("7521262f-d2fc-4770-aa42-3c1152a1b2f9")
                        },
                        new
                        {
                            Id = new Guid("fd9dbdbb-eb45-4c6d-9cd2-90fd6775a4dc"),
                            CreateDate = new DateTime(2024, 5, 22, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3993),
                            Grade = 2,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, ",
                            UserId = new Guid("5ac67651-c217-4fd9-b53c-2520323a361c")
                        },
                        new
                        {
                            Id = new Guid("dee8f162-f14a-4027-86f6-5fd2c9392eb7"),
                            CreateDate = new DateTime(2024, 4, 7, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(3997),
                            Grade = 3,
                            ProductId = new Guid("e7f62158-1a40-475b-8e08-0f41423f50ea"),
                            Rating = 2.9100000000000001,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = new Guid("1be180b1-c6b2-4ab1-8086-d1aa90f02b1e")
                        },
                        new
                        {
                            Id = new Guid("045079eb-0c9c-49ac-a127-36324837fcab"),
                            CreateDate = new DateTime(2024, 4, 5, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4000),
                            Grade = 2,
                            ProductId = new Guid("9a3f181e-96fd-4f2b-9780-7ef25040ade2"),
                            Rating = 2.5699999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, cons",
                            UserId = new Guid("3355e863-0432-4317-a40e-cf0b21b3cc8f")
                        },
                        new
                        {
                            Id = new Guid("4b96e2e1-db7b-47f0-9b7a-a5ed20a4a5a3"),
                            CreateDate = new DateTime(2024, 4, 29, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4003),
                            Grade = 1,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,",
                            UserId = new Guid("c877a2eb-7cd0-4769-98dd-985c6a5b0bb3")
                        },
                        new
                        {
                            Id = new Guid("e4528b09-3605-4b04-9e77-5c1597e6438e"),
                            CreateDate = new DateTime(2024, 3, 21, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4009),
                            Grade = 2,
                            ProductId = new Guid("2c9b6dff-e103-4cd5-99c5-0ae5a824197a"),
                            Rating = 2.3300000000000001,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, conse",
                            UserId = new Guid("0bfbe217-3f50-4676-896d-1d23ca9a4373")
                        },
                        new
                        {
                            Id = new Guid("7a7294cb-3086-4d25-800f-db8d2ac84fa7"),
                            CreateDate = new DateTime(2024, 4, 26, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4014),
                            Grade = 1,
                            ProductId = new Guid("9c1c98c2-2d02-4895-a94e-e87af4799012"),
                            Rating = 3.3300000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, con",
                            UserId = new Guid("3af65851-ea28-4cbe-9568-47af6d2e2073")
                        },
                        new
                        {
                            Id = new Guid("7bd43c74-c307-45fe-beb3-2bcce6dcb65f"),
                            CreateDate = new DateTime(2024, 5, 29, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4017),
                            Grade = 5,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labo",
                            UserId = new Guid("e6a4a7ab-3a91-41de-87de-4d9b04a7d772")
                        },
                        new
                        {
                            Id = new Guid("9721cef0-df2f-4d1e-9e2e-31ad94587f6b"),
                            CreateDate = new DateTime(2024, 2, 28, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4020),
                            Grade = 2,
                            ProductId = new Guid("9c1c98c2-2d02-4895-a94e-e87af4799012"),
                            Rating = 3.3300000000000001,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor",
                            UserId = new Guid("65b897b2-823e-4cbf-91c4-8f482d4ff10a")
                        },
                        new
                        {
                            Id = new Guid("1aaf2ae1-64dd-4da6-a980-94641fe931d4"),
                            CreateDate = new DateTime(2024, 3, 30, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4025),
                            Grade = 5,
                            ProductId = new Guid("a8b6cdb9-0c82-4939-b593-4eca6ca684cf"),
                            Rating = 2.4399999999999999,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisici",
                            UserId = new Guid("8b9d89e6-21b3-4565-8036-aab31b06444b")
                        },
                        new
                        {
                            Id = new Guid("82cca4fa-bdd9-46d4-9db8-302deea391d9"),
                            CreateDate = new DateTime(2024, 3, 31, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4030),
                            Grade = 1,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit ame",
                            UserId = new Guid("9abd369c-fac9-4a1b-87eb-e02e69395f5a")
                        },
                        new
                        {
                            Id = new Guid("e7bb3a5c-e784-45e6-a8cf-3c417fbe2323"),
                            CreateDate = new DateTime(2024, 4, 25, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4034),
                            Grade = 4,
                            ProductId = new Guid("402712e1-1881-4dda-9938-609d104a3ff1"),
                            Rating = 3.3799999999999999,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab",
                            UserId = new Guid("e955eee8-7327-4597-88ce-8d79fa455ec2")
                        },
                        new
                        {
                            Id = new Guid("87bafd7a-f101-4b60-b433-ac86a16247b3"),
                            CreateDate = new DateTime(2024, 4, 25, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4037),
                            Grade = 4,
                            ProductId = new Guid("402712e1-1881-4dda-9938-609d104a3ff1"),
                            Rating = 3.3799999999999999,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor i",
                            UserId = new Guid("fe05f420-a0cc-43fe-b5f3-fca5bc87742f")
                        },
                        new
                        {
                            Id = new Guid("c253417f-16c8-47eb-855b-45ea35546917"),
                            CreateDate = new DateTime(2024, 5, 27, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4042),
                            Grade = 3,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adip",
                            UserId = new Guid("a757cc0d-f00f-4119-a107-979f271dc588")
                        },
                        new
                        {
                            Id = new Guid("89e3ffd2-5aba-41d7-829b-d82160314f68"),
                            CreateDate = new DateTime(2024, 3, 2, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4045),
                            Grade = 4,
                            ProductId = new Guid("402712e1-1881-4dda-9938-609d104a3ff1"),
                            Rating = 3.3799999999999999,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ",
                            UserId = new Guid("251a065b-acb8-4e92-9ad8-036be2a87a88")
                        },
                        new
                        {
                            Id = new Guid("42f54ba3-bd0f-4d02-b54f-b616c98e24c4"),
                            CreateDate = new DateTime(2024, 2, 21, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4048),
                            Grade = 2,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod t",
                            UserId = new Guid("c0f9898a-a1cc-48d1-8da0-291de1f2c3fc")
                        },
                        new
                        {
                            Id = new Guid("9e784e39-2e06-4d95-a1cc-ae3ff8f283a9"),
                            CreateDate = new DateTime(2024, 3, 4, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4051),
                            Grade = 5,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, ",
                            UserId = new Guid("ead05450-c0c7-4088-80cf-f9ec675e4c8f")
                        },
                        new
                        {
                            Id = new Guid("a7fbb741-10b4-4906-a9f3-e9c5e5498134"),
                            CreateDate = new DateTime(2024, 5, 4, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4057),
                            Grade = 4,
                            ProductId = new Guid("e7f62158-1a40-475b-8e08-0f41423f50ea"),
                            Rating = 2.9100000000000001,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = new Guid("65ff2b1f-a2b2-4def-95fe-3676bc926fef")
                        },
                        new
                        {
                            Id = new Guid("49f4a826-ee9a-4dea-bd8a-963ea47d6bd1"),
                            CreateDate = new DateTime(2024, 5, 28, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4107),
                            Grade = 1,
                            ProductId = new Guid("9a3f181e-96fd-4f2b-9780-7ef25040ade2"),
                            Rating = 2.5699999999999998,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = new Guid("43927c98-2d24-4b1e-9c16-bc2007ad52fb")
                        },
                        new
                        {
                            Id = new Guid("521bb1fe-5a65-4c85-8c13-3e6ad09947b7"),
                            CreateDate = new DateTime(2024, 4, 29, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4112),
                            Grade = 2,
                            ProductId = new Guid("9a3f181e-96fd-4f2b-9780-7ef25040ade2"),
                            Rating = 2.5699999999999998,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = new Guid("496f30e2-25bb-4fb2-a6c1-0152a0b3f7ea")
                        },
                        new
                        {
                            Id = new Guid("dc3e0170-039f-43a0-ab34-ea4c108ccc44"),
                            CreateDate = new DateTime(2024, 5, 25, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4116),
                            Grade = 1,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, con",
                            UserId = new Guid("df2a8ca0-315b-40d7-9c7b-4f2f38c7cfbe")
                        },
                        new
                        {
                            Id = new Guid("9f5d3c47-bdec-40fe-a2db-96a3ff5d0805"),
                            CreateDate = new DateTime(2024, 5, 6, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4121),
                            Grade = 2,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labo",
                            UserId = new Guid("c1b180e4-39b4-4e25-a806-a67cffc3eb0d")
                        },
                        new
                        {
                            Id = new Guid("bcbedd95-b301-415e-9dbb-2e686bf3653e"),
                            CreateDate = new DateTime(2024, 4, 17, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4124),
                            Grade = 5,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = new Guid("17d6778c-8509-44f8-8244-32a0dfeaa003")
                        },
                        new
                        {
                            Id = new Guid("5380d3d3-228a-430e-b03e-a326e0de5a7d"),
                            CreateDate = new DateTime(2024, 4, 15, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4127),
                            Grade = 1,
                            ProductId = new Guid("a8b6cdb9-0c82-4939-b593-4eca6ca684cf"),
                            Rating = 2.4399999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = new Guid("e5fa276d-9457-4e07-9c2e-315a649ea65a")
                        },
                        new
                        {
                            Id = new Guid("280e7212-b050-4c43-b35c-29114cb7f824"),
                            CreateDate = new DateTime(2024, 3, 11, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4130),
                            Grade = 1,
                            ProductId = new Guid("a8b6cdb9-0c82-4939-b593-4eca6ca684cf"),
                            Rating = 2.4399999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed ",
                            UserId = new Guid("3ed7c732-6080-4414-b619-592a79e2aced")
                        },
                        new
                        {
                            Id = new Guid("5d0c8993-1584-4a0c-9012-23552169a4ad"),
                            CreateDate = new DateTime(2024, 4, 24, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4135),
                            Grade = 4,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci",
                            UserId = new Guid("b3790f91-5a51-4f08-afbe-ba5028cb8225")
                        },
                        new
                        {
                            Id = new Guid("402802a1-88ea-4e64-95cd-0b145209571b"),
                            CreateDate = new DateTime(2024, 2, 29, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4138),
                            Grade = 3,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = new Guid("5cb58da5-d8b8-4515-9803-c40f38f4f45a")
                        },
                        new
                        {
                            Id = new Guid("360bbc56-235f-44f9-9222-69a7832a6b2a"),
                            CreateDate = new DateTime(2024, 5, 7, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4140),
                            Grade = 3,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo",
                            UserId = new Guid("3c7b5093-cd45-4cae-bcbe-b7e5e59ab13f")
                        },
                        new
                        {
                            Id = new Guid("3e4acc4b-a266-4783-add8-098c7e15a12a"),
                            CreateDate = new DateTime(2024, 2, 23, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4144),
                            Grade = 5,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = new Guid("fcded7eb-c3be-4e69-94d3-fdf97b83d8b6")
                        },
                        new
                        {
                            Id = new Guid("5c05886d-2e29-46de-8316-90e6feadcbf8"),
                            CreateDate = new DateTime(2024, 5, 23, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4149),
                            Grade = 5,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut l",
                            UserId = new Guid("cf22047e-884a-4e9f-b649-82e48177fdd2")
                        },
                        new
                        {
                            Id = new Guid("da074a19-9242-4ab9-b6f4-e8e86a6b7f8e"),
                            CreateDate = new DateTime(2024, 3, 19, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4152),
                            Grade = 2,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisic",
                            UserId = new Guid("7c897a58-70b9-4c6b-b2e3-e3a62cfd8260")
                        },
                        new
                        {
                            Id = new Guid("497c9b38-0a88-4a4d-a4ee-f61fdecfc105"),
                            CreateDate = new DateTime(2024, 3, 8, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4155),
                            Grade = 1,
                            ProductId = new Guid("2c9b6dff-e103-4cd5-99c5-0ae5a824197a"),
                            Rating = 2.3300000000000001,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipi",
                            UserId = new Guid("2646b36e-c36c-4320-b7f9-b0232ce37919")
                        },
                        new
                        {
                            Id = new Guid("9adef1b9-a3b8-4ca7-ad76-d184b3c3c50a"),
                            CreateDate = new DateTime(2024, 2, 28, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4157),
                            Grade = 1,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ",
                            UserId = new Guid("20edbc44-f57c-49c0-964e-c07589fd7daf")
                        },
                        new
                        {
                            Id = new Guid("d6d343e8-8a28-45e6-935a-afb8387cc47d"),
                            CreateDate = new DateTime(2024, 5, 5, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4162),
                            Grade = 1,
                            ProductId = new Guid("e7f62158-1a40-475b-8e08-0f41423f50ea"),
                            Rating = 2.9100000000000001,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi",
                            UserId = new Guid("9ac69867-7efb-430e-a071-bd3d1653495f")
                        },
                        new
                        {
                            Id = new Guid("81813a92-1db7-4491-9230-37458c340900"),
                            CreateDate = new DateTime(2024, 4, 17, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4165),
                            Grade = 1,
                            ProductId = new Guid("218bde1c-db2a-4da7-9115-3e5829d8a237"),
                            Rating = 2.71,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = new Guid("03a2c9f8-3624-4574-826f-7caa2df6ce8c")
                        },
                        new
                        {
                            Id = new Guid("7cd2f849-a9a7-4e68-86ab-58392d8694c4"),
                            CreateDate = new DateTime(2024, 5, 27, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4168),
                            Grade = 4,
                            ProductId = new Guid("402712e1-1881-4dda-9938-609d104a3ff1"),
                            Rating = 3.3799999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = new Guid("142ceb06-e349-4908-bf6d-f1debb413eaa")
                        },
                        new
                        {
                            Id = new Guid("b790421d-eee7-4d04-b4a8-247ee3505982"),
                            CreateDate = new DateTime(2024, 4, 19, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4171),
                            Grade = 5,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor",
                            UserId = new Guid("54f9f648-6600-4c57-974b-543f0f49cbc2")
                        },
                        new
                        {
                            Id = new Guid("e8c24e33-bc3b-494f-ad04-382d3b5a8be9"),
                            CreateDate = new DateTime(2024, 5, 2, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4176),
                            Grade = 1,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor i",
                            UserId = new Guid("5b5dd516-d25b-4b2b-9bb4-6a766f75a95d")
                        },
                        new
                        {
                            Id = new Guid("ffd263f8-6468-44b9-846d-2ca52b0ed98f"),
                            CreateDate = new DateTime(2024, 5, 16, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4179),
                            Grade = 2,
                            ProductId = new Guid("9a3f181e-96fd-4f2b-9780-7ef25040ade2"),
                            Rating = 2.5699999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = new Guid("9f9ab737-48e3-4839-a308-9bc2eeae91da")
                        },
                        new
                        {
                            Id = new Guid("ed5a787a-5173-454b-9519-2c8b4671475e"),
                            CreateDate = new DateTime(2024, 3, 11, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4181),
                            Grade = 1,
                            ProductId = new Guid("2c9b6dff-e103-4cd5-99c5-0ae5a824197a"),
                            Rating = 2.3300000000000001,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = new Guid("3929f73f-396f-48b6-8130-418b685f3c25")
                        },
                        new
                        {
                            Id = new Guid("82974931-3b93-4c8a-a7bd-b59a9cfb6490"),
                            CreateDate = new DateTime(2024, 3, 16, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4185),
                            Grade = 5,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius",
                            UserId = new Guid("a7b04e92-cf22-44d3-ac88-2629a2744c0f")
                        },
                        new
                        {
                            Id = new Guid("dd4b0ab9-d98b-4627-8a23-244f32ea1633"),
                            CreateDate = new DateTime(2024, 4, 16, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4190),
                            Grade = 4,
                            ProductId = new Guid("e7f62158-1a40-475b-8e08-0f41423f50ea"),
                            Rating = 2.9100000000000001,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = new Guid("8e4fccae-50f0-489b-8dad-f8edbbeef6bb")
                        },
                        new
                        {
                            Id = new Guid("3cf9df5a-d371-42a3-8571-4d887ada47fb"),
                            CreateDate = new DateTime(2024, 5, 5, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4193),
                            Grade = 4,
                            ProductId = new Guid("9a3f181e-96fd-4f2b-9780-7ef25040ade2"),
                            Rating = 2.5699999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisi",
                            UserId = new Guid("7e8cd680-8bfe-45c2-bde1-064967d380f6")
                        },
                        new
                        {
                            Id = new Guid("000b02c0-a310-49a5-9265-30ab08e8aea6"),
                            CreateDate = new DateTime(2024, 5, 25, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4195),
                            Grade = 5,
                            ProductId = new Guid("402712e1-1881-4dda-9938-609d104a3ff1"),
                            Rating = 3.3799999999999999,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ",
                            UserId = new Guid("e5399c34-5ab4-4f55-837c-55d408a551c7")
                        },
                        new
                        {
                            Id = new Guid("96245165-e72b-4115-88ea-db84cc277f70"),
                            CreateDate = new DateTime(2024, 4, 14, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4197),
                            Grade = 5,
                            ProductId = new Guid("9a3f181e-96fd-4f2b-9780-7ef25040ade2"),
                            Rating = 2.5699999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = new Guid("4c818fd0-73be-4218-841f-60e2723da2c1")
                        },
                        new
                        {
                            Id = new Guid("11f18401-033b-420d-8414-ac4c625710b5"),
                            CreateDate = new DateTime(2024, 2, 26, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4201),
                            Grade = 4,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed",
                            UserId = new Guid("eb70f592-6e3a-41c9-8d42-8bb864a815fe")
                        },
                        new
                        {
                            Id = new Guid("4d71257a-20b1-4a9b-b2fd-aee6ed76c85d"),
                            CreateDate = new DateTime(2024, 5, 20, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4203),
                            Grade = 4,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labo",
                            UserId = new Guid("83973893-5a31-4a6b-b5f0-e0382104e7c9")
                        },
                        new
                        {
                            Id = new Guid("4b604557-5f50-4973-88e4-ad631eb627df"),
                            CreateDate = new DateTime(2024, 4, 30, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4205),
                            Grade = 5,
                            ProductId = new Guid("218bde1c-db2a-4da7-9115-3e5829d8a237"),
                            Rating = 2.71,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s",
                            UserId = new Guid("b2e1b67d-5b59-45f6-a76f-98fc4970e63e")
                        },
                        new
                        {
                            Id = new Guid("f58fb3e9-dc3f-41fe-ac05-35e0946df210"),
                            CreateDate = new DateTime(2024, 5, 14, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4207),
                            Grade = 5,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adi",
                            UserId = new Guid("5cdf9f64-8d9b-47b4-9eca-19e54d89d41a")
                        },
                        new
                        {
                            Id = new Guid("9c970aa3-6dcd-458f-8928-9c2c82a1531b"),
                            CreateDate = new DateTime(2024, 3, 28, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4211),
                            Grade = 4,
                            ProductId = new Guid("9c1c98c2-2d02-4895-a94e-e87af4799012"),
                            Rating = 3.3300000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = new Guid("82e422f6-8382-49ce-976f-44c8cfa4b548")
                        },
                        new
                        {
                            Id = new Guid("2bb77e0b-3bad-4a35-bd03-01dc4e0b21d8"),
                            CreateDate = new DateTime(2024, 4, 3, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4213),
                            Grade = 2,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi",
                            UserId = new Guid("1fb0717b-5c11-41c4-88bd-fce3a5025531")
                        },
                        new
                        {
                            Id = new Guid("75bd3393-54fb-4b85-8a7a-080e0f34e9ac"),
                            CreateDate = new DateTime(2024, 2, 26, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4243),
                            Grade = 4,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit a",
                            UserId = new Guid("2ce55780-c815-420f-b520-f7789aa8ec19")
                        },
                        new
                        {
                            Id = new Guid("a94215f6-0040-4ff9-922a-6194921f54e6"),
                            CreateDate = new DateTime(2024, 5, 10, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4246),
                            Grade = 5,
                            ProductId = new Guid("218bde1c-db2a-4da7-9115-3e5829d8a237"),
                            Rating = 2.71,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = new Guid("e08bf893-b0b8-4589-a27c-28e525a2930a")
                        },
                        new
                        {
                            Id = new Guid("6e3a541e-bc16-48d7-b1d7-44789bf26ce1"),
                            CreateDate = new DateTime(2024, 3, 5, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4250),
                            Grade = 2,
                            ProductId = new Guid("e7f62158-1a40-475b-8e08-0f41423f50ea"),
                            Rating = 2.9100000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, c",
                            UserId = new Guid("daf0c8b6-f524-42c2-96a3-3414c6a46491")
                        },
                        new
                        {
                            Id = new Guid("f15eee93-cb49-4b0a-becb-b29fe1fb6c95"),
                            CreateDate = new DateTime(2024, 3, 18, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4252),
                            Grade = 3,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s",
                            UserId = new Guid("415f85e2-0fc6-43f7-9241-128d8ae8d4ce")
                        },
                        new
                        {
                            Id = new Guid("d4042447-d732-44da-90e9-f816f2f39f55"),
                            CreateDate = new DateTime(2024, 3, 31, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4255),
                            Grade = 2,
                            ProductId = new Guid("2c9b6dff-e103-4cd5-99c5-0ae5a824197a"),
                            Rating = 2.3300000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adip",
                            UserId = new Guid("c5896b42-36a2-4627-9b40-fc19dfaa0b86")
                        },
                        new
                        {
                            Id = new Guid("15707a63-1176-46ff-baef-289f2d0ec088"),
                            CreateDate = new DateTime(2024, 4, 19, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4256),
                            Grade = 1,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = new Guid("0aaaa193-9f3e-45cc-bdad-ae20b12628f2")
                        },
                        new
                        {
                            Id = new Guid("4f0e467a-e6f0-4256-b492-a7571f7ccb8e"),
                            CreateDate = new DateTime(2024, 3, 15, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4260),
                            Grade = 2,
                            ProductId = new Guid("402712e1-1881-4dda-9938-609d104a3ff1"),
                            Rating = 3.3799999999999999,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = new Guid("20508059-6474-4d90-b622-3aa96f7d1a84")
                        },
                        new
                        {
                            Id = new Guid("b49d8b2a-d928-4d74-8a23-1cf9c95a8bc0"),
                            CreateDate = new DateTime(2024, 3, 29, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4263),
                            Grade = 1,
                            ProductId = new Guid("a8b6cdb9-0c82-4939-b593-4eca6ca684cf"),
                            Rating = 2.4399999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo",
                            UserId = new Guid("27df37f9-e2f4-4182-b6cb-f8b1ff3c032a")
                        },
                        new
                        {
                            Id = new Guid("8e055fd3-0c1f-4a11-8b86-4cdc9d922886"),
                            CreateDate = new DateTime(2024, 5, 23, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4265),
                            Grade = 3,
                            ProductId = new Guid("218bde1c-db2a-4da7-9115-3e5829d8a237"),
                            Rating = 2.71,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = new Guid("e64d7de1-5cf4-49fb-bc31-19d705968207")
                        },
                        new
                        {
                            Id = new Guid("1e14d7c0-df27-4529-b7e7-fe1fa139ad26"),
                            CreateDate = new DateTime(2024, 5, 13, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4267),
                            Grade = 3,
                            ProductId = new Guid("9c1c98c2-2d02-4895-a94e-e87af4799012"),
                            Rating = 3.3300000000000001,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab",
                            UserId = new Guid("948a0022-0a08-4e5a-9a21-bfa8a64df18b")
                        },
                        new
                        {
                            Id = new Guid("9c6f09e1-e4c9-44a2-adeb-094aba3fffaa"),
                            CreateDate = new DateTime(2024, 4, 7, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4271),
                            Grade = 5,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipi",
                            UserId = new Guid("f036fb2e-5824-406c-a0e8-31b9df02a987")
                        },
                        new
                        {
                            Id = new Guid("b45d3a1d-caac-4ba6-9a00-389ba7b1cb55"),
                            CreateDate = new DateTime(2024, 5, 28, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4272),
                            Grade = 1,
                            ProductId = new Guid("2c9b6dff-e103-4cd5-99c5-0ae5a824197a"),
                            Rating = 2.3300000000000001,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, ",
                            UserId = new Guid("bf497832-e349-4546-9d6a-b6c0bf738f7a")
                        },
                        new
                        {
                            Id = new Guid("5de9f2d6-fe97-45ac-80ee-2757291f1d53"),
                            CreateDate = new DateTime(2024, 4, 13, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4274),
                            Grade = 4,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = new Guid("d7059db4-2ca0-40e3-8579-f810b169ded4")
                        },
                        new
                        {
                            Id = new Guid("ae7c96b1-36de-450f-b524-6943809cd3b3"),
                            CreateDate = new DateTime(2024, 2, 27, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4277),
                            Grade = 5,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s",
                            UserId = new Guid("d85a0e8f-66d8-4d3e-8943-bd2b0ae5e8cc")
                        },
                        new
                        {
                            Id = new Guid("ac32eed7-6148-4c1c-94b0-4dabf2badc1b"),
                            CreateDate = new DateTime(2024, 3, 26, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4280),
                            Grade = 2,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectet",
                            UserId = new Guid("e700380c-9d3b-4f5b-ac8d-cea70e4953f3")
                        },
                        new
                        {
                            Id = new Guid("085744f0-8fbe-40cf-ba49-821d9ff3b1fd"),
                            CreateDate = new DateTime(2024, 3, 19, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4282),
                            Grade = 5,
                            ProductId = new Guid("a8b6cdb9-0c82-4939-b593-4eca6ca684cf"),
                            Rating = 2.4399999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ei",
                            UserId = new Guid("60fce0c2-1cce-4a5b-ab6d-9f701967a369")
                        },
                        new
                        {
                            Id = new Guid("fa0bcace-c04e-4ed1-9515-11cc46f2a252"),
                            CreateDate = new DateTime(2024, 4, 11, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4284),
                            Grade = 4,
                            ProductId = new Guid("e7f62158-1a40-475b-8e08-0f41423f50ea"),
                            Rating = 2.9100000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut l",
                            UserId = new Guid("fde8a90c-20fd-4ae2-9cbe-0c581ee520d9")
                        },
                        new
                        {
                            Id = new Guid("3baece53-cd62-4757-980f-7eb9e319a517"),
                            CreateDate = new DateTime(2024, 4, 15, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4286),
                            Grade = 4,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,",
                            UserId = new Guid("da2e42a9-79cf-4c1b-ac74-e01b7964f102")
                        },
                        new
                        {
                            Id = new Guid("0ac83349-2cbf-4a92-b456-2159bf9c2cc0"),
                            CreateDate = new DateTime(2024, 2, 28, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4290),
                            Grade = 2,
                            ProductId = new Guid("e7f62158-1a40-475b-8e08-0f41423f50ea"),
                            Rating = 2.9100000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = new Guid("f94ab6ac-ac88-4a30-a787-500922694e5c")
                        },
                        new
                        {
                            Id = new Guid("f28a867a-8bb4-481b-b8b4-caf7181cb2dd"),
                            CreateDate = new DateTime(2024, 4, 21, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4292),
                            Grade = 2,
                            ProductId = new Guid("9a3f181e-96fd-4f2b-9780-7ef25040ade2"),
                            Rating = 2.5699999999999998,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing el",
                            UserId = new Guid("c4dd0f24-26e3-45ca-81dc-eeb0f86222a5")
                        },
                        new
                        {
                            Id = new Guid("5ab2fca1-8769-4af8-8d80-637b8e0658d3"),
                            CreateDate = new DateTime(2024, 4, 15, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4294),
                            Grade = 2,
                            ProductId = new Guid("218bde1c-db2a-4da7-9115-3e5829d8a237"),
                            Rating = 2.71,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = new Guid("3d4d3190-318f-4ba7-aa16-53ffc7d6802d")
                        },
                        new
                        {
                            Id = new Guid("544d9fff-4667-45dc-972d-f0a8b2acaf12"),
                            CreateDate = new DateTime(2024, 4, 13, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4296),
                            Grade = 5,
                            ProductId = new Guid("2122622b-b761-4e86-9cab-7c8fd7b4b4f5"),
                            Rating = 3.5299999999999998,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod t",
                            UserId = new Guid("c1db6edc-0370-4817-b1d2-ddd254e11d4f")
                        },
                        new
                        {
                            Id = new Guid("f221aa42-5f3d-4e8f-b4f1-d7dd73989ab9"),
                            CreateDate = new DateTime(2024, 4, 21, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4300),
                            Grade = 1,
                            ProductId = new Guid("e7f62158-1a40-475b-8e08-0f41423f50ea"),
                            Rating = 2.9100000000000001,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisici",
                            UserId = new Guid("6ad6d15f-3aeb-41b1-a19b-b8eb21b3b307")
                        },
                        new
                        {
                            Id = new Guid("76081624-3141-4111-903a-e971d5e776aa"),
                            CreateDate = new DateTime(2024, 4, 19, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4302),
                            Grade = 2,
                            ProductId = new Guid("218bde1c-db2a-4da7-9115-3e5829d8a237"),
                            Rating = 2.71,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = new Guid("0f08b0dc-d9e0-4963-ba01-be34c3a05dae")
                        },
                        new
                        {
                            Id = new Guid("2250a4e3-eb01-4a01-bdf5-8c3ccae13fb6"),
                            CreateDate = new DateTime(2024, 3, 29, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4304),
                            Grade = 3,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiu",
                            UserId = new Guid("17d98a90-9877-411a-8090-cf424da517c0")
                        },
                        new
                        {
                            Id = new Guid("86f4efb1-1285-4f1e-b904-3c70a30c9ec4"),
                            CreateDate = new DateTime(2024, 3, 13, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4305),
                            Grade = 3,
                            ProductId = new Guid("a8b6cdb9-0c82-4939-b593-4eca6ca684cf"),
                            Rating = 2.4399999999999999,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incid",
                            UserId = new Guid("a2da0739-e53a-45ec-bff6-ff40a63c9edb")
                        },
                        new
                        {
                            Id = new Guid("7814f90d-781f-404e-8665-4aab1caf1f9d"),
                            CreateDate = new DateTime(2024, 3, 8, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4309),
                            Grade = 4,
                            ProductId = new Guid("a8b6cdb9-0c82-4939-b593-4eca6ca684cf"),
                            Rating = 2.4399999999999999,
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = new Guid("181cd608-b873-4ed3-a00a-09156b16a9a8")
                        },
                        new
                        {
                            Id = new Guid("5a1f19b5-ac30-4927-92b2-13f2cf2244b5"),
                            CreateDate = new DateTime(2024, 2, 25, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4311),
                            Grade = 4,
                            ProductId = new Guid("2c9b6dff-e103-4cd5-99c5-0ae5a824197a"),
                            Rating = 2.3300000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing ",
                            UserId = new Guid("e92a8d26-266c-484f-a630-cfb4ecf186e5")
                        },
                        new
                        {
                            Id = new Guid("95f93462-b3ba-482d-a609-86793ed35be8"),
                            CreateDate = new DateTime(2024, 4, 22, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4313),
                            Grade = 1,
                            ProductId = new Guid("d5eb1499-46dc-47d8-8a59-ed266837ca79"),
                            Rating = 2.75,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur ",
                            UserId = new Guid("f02e6239-4d82-4e51-bdb5-8a6ca178a42d")
                        },
                        new
                        {
                            Id = new Guid("27785da6-cc36-43b9-a63d-2515228890ad"),
                            CreateDate = new DateTime(2024, 3, 25, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4315),
                            Grade = 2,
                            ProductId = new Guid("f9f23328-a9c1-4ee8-83ff-d99acab5e4b4"),
                            Rating = 2.9199999999999999,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ",
                            UserId = new Guid("76b53df5-4241-4695-9ab2-a2dbc720c3f6")
                        },
                        new
                        {
                            Id = new Guid("8520ede9-c8d7-45e0-81aa-ef1484db66d0"),
                            CreateDate = new DateTime(2024, 5, 9, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4319),
                            Grade = 5,
                            ProductId = new Guid("2c9b6dff-e103-4cd5-99c5-0ae5a824197a"),
                            Rating = 2.3300000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = new Guid("e1603799-bb2b-4479-bfb4-264c8bc9b2f3")
                        },
                        new
                        {
                            Id = new Guid("7a1f681b-f8d3-46a0-8b3e-0730e9c0774d"),
                            CreateDate = new DateTime(2024, 4, 15, 15, 36, 43, 12, DateTimeKind.Local).AddTicks(4321),
                            Grade = 5,
                            ProductId = new Guid("e7f62158-1a40-475b-8e08-0f41423f50ea"),
                            Rating = 2.9100000000000001,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = new Guid("8245205f-fb72-401e-9799-84612bc40aab")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
