// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review.Domain;

#nullable disable

namespace Review.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240612115618_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Review.Domain.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75c5f2d1-02ec-4ff0-85b2-414fdeaede12"),
                            CreateDate = new DateTime(2024, 5, 19, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5330),
                            Grade = 5,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo",
                            UserId = new Guid("e6adfe7c-c07f-4c5b-8369-0a9a743d7476")
                        },
                        new
                        {
                            Id = new Guid("804df8bc-37ce-4990-a6a5-e9e88ac3f048"),
                            CreateDate = new DateTime(2024, 4, 28, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5361),
                            Grade = 1,
                            ProductId = new Guid("9df7c89c-d1aa-4821-9141-bd0747b422e4"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = new Guid("0f342a6b-96c2-417d-adb4-a89a844a2eda")
                        },
                        new
                        {
                            Id = new Guid("0ff0af25-2b52-46c3-9345-f422688717b9"),
                            CreateDate = new DateTime(2024, 4, 23, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5369),
                            Grade = 1,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, conse",
                            UserId = new Guid("5646a74f-46b1-4944-bd2f-a4df0eb86160")
                        },
                        new
                        {
                            Id = new Guid("b6e505e5-17e5-42d3-9935-7f2f8904b73a"),
                            CreateDate = new DateTime(2024, 3, 5, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5375),
                            Grade = 5,
                            ProductId = new Guid("f48175a5-d13a-4780-a281-82936eb6faf3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = new Guid("9180d272-39a1-4cf3-921b-bb3179b655d3")
                        },
                        new
                        {
                            Id = new Guid("bf0655f7-69ea-4d82-92b4-539ad5ef83cb"),
                            CreateDate = new DateTime(2024, 5, 3, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5382),
                            Grade = 3,
                            ProductId = new Guid("e017232b-40b2-4f63-85fd-9e0bc16b238f"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipis",
                            UserId = new Guid("3f2d1419-5cc3-469d-aacc-3cf4c3bf0beb")
                        },
                        new
                        {
                            Id = new Guid("1a8689bb-ca79-4eb2-9671-5547924d1736"),
                            CreateDate = new DateTime(2024, 4, 1, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5392),
                            Grade = 4,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisici",
                            UserId = new Guid("3cfd4d3e-99b9-40b8-a805-4d56e8893015")
                        },
                        new
                        {
                            Id = new Guid("3d8829e9-151c-45c6-a80d-f8695c9bae8a"),
                            CreateDate = new DateTime(2024, 5, 23, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5397),
                            Grade = 4,
                            ProductId = new Guid("f48175a5-d13a-4780-a281-82936eb6faf3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur ",
                            UserId = new Guid("8ac9c24c-5bb6-4ed6-9c16-5ad4351964cb")
                        },
                        new
                        {
                            Id = new Guid("15b18528-6758-4ca1-aee5-e7a36290ced1"),
                            CreateDate = new DateTime(2024, 6, 1, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5402),
                            Grade = 4,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing el",
                            UserId = new Guid("c8c4dd52-e427-449d-8d0d-021ad4b7c01a")
                        },
                        new
                        {
                            Id = new Guid("7fb48216-56f6-45d1-b4fc-9fdec1d993af"),
                            CreateDate = new DateTime(2024, 3, 31, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5408),
                            Grade = 1,
                            ProductId = new Guid("f48175a5-d13a-4780-a281-82936eb6faf3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = new Guid("b1ac818b-286b-431f-9e79-62ead6fcb39c")
                        },
                        new
                        {
                            Id = new Guid("11e74d2b-d72d-42ca-a7d3-64f706a58710"),
                            CreateDate = new DateTime(2024, 3, 11, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5418),
                            Grade = 5,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipis",
                            UserId = new Guid("67020f83-d4ac-4d32-957a-ea8108ee1502")
                        },
                        new
                        {
                            Id = new Guid("5f4f5331-ef0c-4b3c-b0cb-47d15852c75a"),
                            CreateDate = new DateTime(2024, 5, 2, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5423),
                            Grade = 2,
                            ProductId = new Guid("89637c57-614c-4403-b5ef-78dfa6b6f5d1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisici",
                            UserId = new Guid("8c8f7868-1528-4547-a442-f9cc19f011d4")
                        },
                        new
                        {
                            Id = new Guid("73d0bca8-7440-46e3-bf00-c9bd41acc1ca"),
                            CreateDate = new DateTime(2024, 5, 12, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5429),
                            Grade = 2,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisi",
                            UserId = new Guid("585171c4-cb78-4c35-82fe-1cf1614abf14")
                        },
                        new
                        {
                            Id = new Guid("4a45a475-25b6-447b-9f95-bf371108573e"),
                            CreateDate = new DateTime(2024, 5, 28, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5434),
                            Grade = 5,
                            ProductId = new Guid("89637c57-614c-4403-b5ef-78dfa6b6f5d1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor si",
                            UserId = new Guid("f4f3471a-dd84-4c85-8c0d-2ad2290f028e")
                        },
                        new
                        {
                            Id = new Guid("19ec384c-9d21-41ca-90b8-88bf147bdd31"),
                            CreateDate = new DateTime(2024, 4, 25, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5523),
                            Grade = 2,
                            ProductId = new Guid("9df7c89c-d1aa-4821-9141-bd0747b422e4"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididun",
                            UserId = new Guid("252763d4-e0c2-4d09-a3af-b4d66e381bee")
                        },
                        new
                        {
                            Id = new Guid("e83eb01e-b7b0-4601-8c73-becbd42f2937"),
                            CreateDate = new DateTime(2024, 3, 13, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5531),
                            Grade = 4,
                            ProductId = new Guid("89637c57-614c-4403-b5ef-78dfa6b6f5d1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor",
                            UserId = new Guid("b8a8f046-f69b-42b4-a6ce-319c3b2d2cd5")
                        },
                        new
                        {
                            Id = new Guid("d10e2f30-2beb-4e8b-a9e9-caace65f7ac2"),
                            CreateDate = new DateTime(2024, 4, 27, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5537),
                            Grade = 3,
                            ProductId = new Guid("f48175a5-d13a-4780-a281-82936eb6faf3"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = new Guid("d8770a6f-906a-454e-9976-3e120d59ca69")
                        },
                        new
                        {
                            Id = new Guid("2f5df07a-7ddb-4ecf-a59d-e96bf352c242"),
                            CreateDate = new DateTime(2024, 3, 28, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5541),
                            Grade = 2,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisic",
                            UserId = new Guid("db89bc8e-7042-467b-8301-ed45493f4d3b")
                        },
                        new
                        {
                            Id = new Guid("85719a54-ee28-403e-9ca6-f9d11e2ac9a4"),
                            CreateDate = new DateTime(2024, 4, 26, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5550),
                            Grade = 3,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = new Guid("37ff1247-35bd-4bcc-b9e7-080b9ebc06de")
                        },
                        new
                        {
                            Id = new Guid("7fa264d5-765f-4e72-95b2-bf89b0a1089f"),
                            CreateDate = new DateTime(2024, 4, 10, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5556),
                            Grade = 5,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod t",
                            UserId = new Guid("74e5a3f6-ed27-40a1-aa2b-4817bfce428c")
                        },
                        new
                        {
                            Id = new Guid("bb2c14ef-8004-4bb9-a90b-e27e62111c2c"),
                            CreateDate = new DateTime(2024, 3, 31, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5561),
                            Grade = 3,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, cons",
                            UserId = new Guid("c7c985d3-831a-4895-8654-ddb7e8a97c4b")
                        },
                        new
                        {
                            Id = new Guid("7edb09cf-6044-4c9b-82c4-828f9f3f0cad"),
                            CreateDate = new DateTime(2024, 3, 6, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5567),
                            Grade = 4,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing eli",
                            UserId = new Guid("9cb3d785-d94f-44f5-96bb-c3852e65a092")
                        },
                        new
                        {
                            Id = new Guid("ef729ec9-ff0e-445e-812d-70c9400d3822"),
                            CreateDate = new DateTime(2024, 3, 18, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5577),
                            Grade = 3,
                            ProductId = new Guid("7d82582d-4bce-4eca-8cd8-0f1431301e00"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor ",
                            UserId = new Guid("56e68ef1-0cc9-467c-954d-17c26b416c4b")
                        },
                        new
                        {
                            Id = new Guid("0a56ab9b-42e2-466a-a0d2-fe70aecd5827"),
                            CreateDate = new DateTime(2024, 4, 3, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5582),
                            Grade = 1,
                            ProductId = new Guid("f48175a5-d13a-4780-a281-82936eb6faf3"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, co",
                            UserId = new Guid("fb6f560a-7933-4234-8973-740f7abbc179")
                        },
                        new
                        {
                            Id = new Guid("62de710f-9f57-4f9e-ba1c-d579b7ccfcc6"),
                            CreateDate = new DateTime(2024, 4, 16, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5588),
                            Grade = 1,
                            ProductId = new Guid("f48175a5-d13a-4780-a281-82936eb6faf3"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = new Guid("6f5eaae6-a9d7-47d7-b8b0-841eaff0b946")
                        },
                        new
                        {
                            Id = new Guid("d9a72cef-330b-4aff-9217-e019a26cc1d8"),
                            CreateDate = new DateTime(2024, 5, 19, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5594),
                            Grade = 3,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut",
                            UserId = new Guid("3edef6c1-b234-4500-b35a-1368d6f92255")
                        },
                        new
                        {
                            Id = new Guid("1b639caa-5b6b-4802-a70a-56d08e8c4a36"),
                            CreateDate = new DateTime(2024, 6, 9, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5604),
                            Grade = 3,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = new Guid("0e31b9eb-99aa-4f1f-a834-0d2193b31fb0")
                        },
                        new
                        {
                            Id = new Guid("c7d0ef3b-2bd8-4f44-9191-597091e4e0d1"),
                            CreateDate = new DateTime(2024, 3, 22, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5609),
                            Grade = 5,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing eli",
                            UserId = new Guid("cddd7eab-a340-4928-a737-19fa7675e4b2")
                        },
                        new
                        {
                            Id = new Guid("061a1767-696c-4f34-8de9-1b4668ae3452"),
                            CreateDate = new DateTime(2024, 4, 25, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5614),
                            Grade = 2,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = new Guid("dae7e8db-83c8-4340-9e7d-02fe8bf6dbb6")
                        },
                        new
                        {
                            Id = new Guid("27a0763d-291a-4714-9865-90ede61d178e"),
                            CreateDate = new DateTime(2024, 4, 13, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5620),
                            Grade = 3,
                            ProductId = new Guid("f48175a5-d13a-4780-a281-82936eb6faf3"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusm",
                            UserId = new Guid("68c3350f-e338-4fdc-8caa-a11133576299")
                        },
                        new
                        {
                            Id = new Guid("e33fe618-666d-4b69-9c5e-dbb72bebbcec"),
                            CreateDate = new DateTime(2024, 3, 5, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5629),
                            Grade = 1,
                            ProductId = new Guid("7256b740-9a41-4830-9969-7de9a142c37e"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labo",
                            UserId = new Guid("6fb60e82-0bb4-4a6b-aaa3-e357c78c2768")
                        },
                        new
                        {
                            Id = new Guid("06749f5d-413d-465f-9a07-8c69ded8e774"),
                            CreateDate = new DateTime(2024, 4, 10, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5635),
                            Grade = 3,
                            ProductId = new Guid("7256b740-9a41-4830-9969-7de9a142c37e"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor",
                            UserId = new Guid("a5021470-4ce1-4390-99c9-09945de96399")
                        },
                        new
                        {
                            Id = new Guid("a4eef6d1-932f-4bd6-8bc7-6df690c26afd"),
                            CreateDate = new DateTime(2024, 5, 25, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5640),
                            Grade = 3,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = new Guid("5c8b9efe-8315-40a1-aed7-0cd6437970bf")
                        },
                        new
                        {
                            Id = new Guid("90b776cc-f503-4737-b1fd-34173d172b54"),
                            CreateDate = new DateTime(2024, 5, 4, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5646),
                            Grade = 3,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = new Guid("4c255118-de7e-427c-ba83-75e5cfc8fe68")
                        },
                        new
                        {
                            Id = new Guid("5a65ae0e-47e1-4141-a83a-feca7d6d3f9e"),
                            CreateDate = new DateTime(2024, 6, 6, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5655),
                            Grade = 1,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = new Guid("947115eb-803c-48ee-b815-8fd59463df6a")
                        },
                        new
                        {
                            Id = new Guid("cd9ab7e9-2825-4051-8966-1636e980e3f8"),
                            CreateDate = new DateTime(2024, 3, 6, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5661),
                            Grade = 1,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius",
                            UserId = new Guid("6e066afa-b5e1-4f58-bbc5-442116e06025")
                        },
                        new
                        {
                            Id = new Guid("294e2b62-d109-44a9-8039-fdee95e29391"),
                            CreateDate = new DateTime(2024, 5, 26, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5666),
                            Grade = 5,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consec",
                            UserId = new Guid("429adb87-0220-41b4-90be-b2bace57aea7")
                        },
                        new
                        {
                            Id = new Guid("c5c79e67-76c5-480a-ba21-347ecb32e2ab"),
                            CreateDate = new DateTime(2024, 5, 10, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5672),
                            Grade = 2,
                            ProductId = new Guid("9df7c89c-d1aa-4821-9141-bd0747b422e4"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci",
                            UserId = new Guid("c6057d37-597f-436b-8e94-14a0a1046f6f")
                        },
                        new
                        {
                            Id = new Guid("1f21d6ac-5762-4c9a-ae1e-8256b9c2a825"),
                            CreateDate = new DateTime(2024, 4, 1, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5682),
                            Grade = 2,
                            ProductId = new Guid("9df7c89c-d1aa-4821-9141-bd0747b422e4"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut",
                            UserId = new Guid("53de6c45-ecf5-4936-9ed0-2f5ce6deff46")
                        },
                        new
                        {
                            Id = new Guid("5fac6a65-fbe9-48f2-afd0-c109e1cb7500"),
                            CreateDate = new DateTime(2024, 5, 29, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5688),
                            Grade = 4,
                            ProductId = new Guid("89637c57-614c-4403-b5ef-78dfa6b6f5d1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = new Guid("e6f0372c-9011-4872-bbbf-d26180be08a9")
                        },
                        new
                        {
                            Id = new Guid("352bb673-fdad-44e2-8fce-f7325111205b"),
                            CreateDate = new DateTime(2024, 4, 11, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5694),
                            Grade = 5,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing",
                            UserId = new Guid("7857f939-7d9d-497b-a350-834b1ba2ca19")
                        },
                        new
                        {
                            Id = new Guid("97a65a8e-fcb4-47e6-a935-ee7fb55102ea"),
                            CreateDate = new DateTime(2024, 5, 18, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5699),
                            Grade = 5,
                            ProductId = new Guid("e017232b-40b2-4f63-85fd-9e0bc16b238f"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adi",
                            UserId = new Guid("54e50494-57f1-448b-bd63-b7668c12b372")
                        },
                        new
                        {
                            Id = new Guid("b11b9ea8-5e14-4846-a8e9-c3cb119e371c"),
                            CreateDate = new DateTime(2024, 3, 23, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5709),
                            Grade = 4,
                            ProductId = new Guid("89637c57-614c-4403-b5ef-78dfa6b6f5d1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s",
                            UserId = new Guid("f8d8b083-99a1-4e93-a4d8-cfe778a10635")
                        },
                        new
                        {
                            Id = new Guid("6990c7d9-8d62-4aa3-9492-3d0d03dd8177"),
                            CreateDate = new DateTime(2024, 3, 14, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5714),
                            Grade = 5,
                            ProductId = new Guid("7256b740-9a41-4830-9969-7de9a142c37e"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = new Guid("7293b215-f6d1-49e6-a219-c11fed9315e3")
                        },
                        new
                        {
                            Id = new Guid("89c2e510-4bde-4f0f-a430-f3fb9b8d6808"),
                            CreateDate = new DateTime(2024, 3, 27, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5719),
                            Grade = 4,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = new Guid("b45de52d-0479-4525-8a07-f0fa0e76cf2b")
                        },
                        new
                        {
                            Id = new Guid("d1668950-3acc-4bdd-a9c9-1a9c9adf08f5"),
                            CreateDate = new DateTime(2024, 5, 3, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5724),
                            Grade = 5,
                            ProductId = new Guid("e017232b-40b2-4f63-85fd-9e0bc16b238f"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, ",
                            UserId = new Guid("36c0469f-403a-4b5d-9a0b-a3d49bc0e9bf")
                        },
                        new
                        {
                            Id = new Guid("fea5850b-94de-4ecf-9d3c-583437c3e3f1"),
                            CreateDate = new DateTime(2024, 5, 11, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5733),
                            Grade = 5,
                            ProductId = new Guid("e017232b-40b2-4f63-85fd-9e0bc16b238f"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consec",
                            UserId = new Guid("734180f4-cb66-47c3-b285-7bf59bbba313")
                        },
                        new
                        {
                            Id = new Guid("ef9a91da-311e-4d50-90ae-b64210c46fa7"),
                            CreateDate = new DateTime(2024, 3, 4, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5738),
                            Grade = 5,
                            ProductId = new Guid("7256b740-9a41-4830-9969-7de9a142c37e"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, conse",
                            UserId = new Guid("abdfa596-079d-4452-a826-0f5e84ff36b0")
                        },
                        new
                        {
                            Id = new Guid("4a70d1bc-c27a-4b17-828f-7fd816ebb704"),
                            CreateDate = new DateTime(2024, 6, 6, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5800),
                            Grade = 4,
                            ProductId = new Guid("7d82582d-4bce-4eca-8cd8-0f1431301e00"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi",
                            UserId = new Guid("549b1e41-4180-449b-bd71-b300a0269475")
                        },
                        new
                        {
                            Id = new Guid("b84cbef7-7a9d-4352-a248-403cd678e60b"),
                            CreateDate = new DateTime(2024, 3, 19, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5807),
                            Grade = 2,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = new Guid("9c3dc7ac-b21e-4966-98ec-ddddabe40b59")
                        },
                        new
                        {
                            Id = new Guid("b5f8006d-70a1-4e24-91bd-7679dd4f1c7d"),
                            CreateDate = new DateTime(2024, 3, 8, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5817),
                            Grade = 3,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidid",
                            UserId = new Guid("0aeac3f9-bcbc-4331-9eb3-6f8019b8ca73")
                        },
                        new
                        {
                            Id = new Guid("85ad674a-7100-49c8-91e3-335e1cbe021d"),
                            CreateDate = new DateTime(2024, 6, 7, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5823),
                            Grade = 5,
                            ProductId = new Guid("9df7c89c-d1aa-4821-9141-bd0747b422e4"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius",
                            UserId = new Guid("caf25aee-36e1-4856-b74a-3fbb1c7a8f67")
                        },
                        new
                        {
                            Id = new Guid("88ab22c0-0e46-482a-9a6b-360a78a155be"),
                            CreateDate = new DateTime(2024, 3, 14, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5829),
                            Grade = 1,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ",
                            UserId = new Guid("b0f4d157-3f4b-4dc3-a3e5-bcf57a381db7")
                        },
                        new
                        {
                            Id = new Guid("50ab0017-040f-4efd-a234-b3b491327843"),
                            CreateDate = new DateTime(2024, 3, 29, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5833),
                            Grade = 3,
                            ProductId = new Guid("89637c57-614c-4403-b5ef-78dfa6b6f5d1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ",
                            UserId = new Guid("8165ee72-f364-4bd4-9c18-e59a329e4206")
                        },
                        new
                        {
                            Id = new Guid("af89163b-e131-4e88-a056-92035333378b"),
                            CreateDate = new DateTime(2024, 3, 15, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5843),
                            Grade = 3,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing e",
                            UserId = new Guid("36e938ea-4e43-48f8-8167-662b5dfbbb33")
                        },
                        new
                        {
                            Id = new Guid("b0f9b759-0514-4b50-914b-8d310012c862"),
                            CreateDate = new DateTime(2024, 6, 6, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5848),
                            Grade = 1,
                            ProductId = new Guid("e017232b-40b2-4f63-85fd-9e0bc16b238f"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s",
                            UserId = new Guid("70090607-353e-4e7e-9f2a-6f9e50af7abf")
                        },
                        new
                        {
                            Id = new Guid("f66be22e-c300-4bf6-b700-09a94a210fa0"),
                            CreateDate = new DateTime(2024, 4, 13, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5853),
                            Grade = 1,
                            ProductId = new Guid("9df7c89c-d1aa-4821-9141-bd0747b422e4"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = new Guid("2d3a9ec6-44c3-4ba4-9374-738a29d38da5")
                        },
                        new
                        {
                            Id = new Guid("b8ace4a2-59b1-4352-9355-38fdae45c768"),
                            CreateDate = new DateTime(2024, 4, 26, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5858),
                            Grade = 1,
                            ProductId = new Guid("7d82582d-4bce-4eca-8cd8-0f1431301e00"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ",
                            UserId = new Guid("e97568c3-606a-4025-8c50-317cee639d58")
                        },
                        new
                        {
                            Id = new Guid("225937bf-6e20-43b4-a031-41f74a0150ee"),
                            CreateDate = new DateTime(2024, 3, 28, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5866),
                            Grade = 1,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu",
                            UserId = new Guid("675fba47-0eaf-4428-8a8e-646e3148260d")
                        },
                        new
                        {
                            Id = new Guid("6eb34e7d-f8cc-4f32-bd92-7a58eac58787"),
                            CreateDate = new DateTime(2024, 3, 7, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5872),
                            Grade = 1,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur ad",
                            UserId = new Guid("8af28303-d9cd-4b78-bf50-8bd7067a8fd5")
                        },
                        new
                        {
                            Id = new Guid("1f911a67-1ba5-4f35-8097-c8075ea99bad"),
                            CreateDate = new DateTime(2024, 3, 20, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5878),
                            Grade = 4,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur ",
                            UserId = new Guid("cf90f1c3-379e-4e29-bab3-a5bb7228fc4e")
                        },
                        new
                        {
                            Id = new Guid("be6bb112-bf63-4d70-8e49-9ea26ddbc7c3"),
                            CreateDate = new DateTime(2024, 5, 23, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5883),
                            Grade = 5,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = new Guid("a1522b6a-5f3c-41eb-813f-740b6ae3db30")
                        },
                        new
                        {
                            Id = new Guid("dba6134b-fb45-4e63-acb9-f9fd411cf4c6"),
                            CreateDate = new DateTime(2024, 5, 16, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5892),
                            Grade = 2,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, se",
                            UserId = new Guid("55e6d687-cbc7-4aa5-9d7c-0e328505943e")
                        },
                        new
                        {
                            Id = new Guid("08ab9a07-2165-4ba0-a40f-e5add88c7c84"),
                            CreateDate = new DateTime(2024, 6, 3, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5898),
                            Grade = 2,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labo",
                            UserId = new Guid("b706d771-df8c-47f6-b231-f9a836ab9a48")
                        },
                        new
                        {
                            Id = new Guid("c9f49452-de5f-42b5-8637-52f36c4f761b"),
                            CreateDate = new DateTime(2024, 5, 31, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5903),
                            Grade = 5,
                            ProductId = new Guid("d1ce2397-ef20-4559-abe4-7118d3cf2159"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = new Guid("5b1d99bb-1bba-4ab7-bd8a-fa080b320dc2")
                        },
                        new
                        {
                            Id = new Guid("2e36854d-3684-4a7a-89fe-4873c5b64325"),
                            CreateDate = new DateTime(2024, 5, 10, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5908),
                            Grade = 3,
                            ProductId = new Guid("e017232b-40b2-4f63-85fd-9e0bc16b238f"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectet",
                            UserId = new Guid("f048e17f-66c4-4559-a548-8a556a3df709")
                        },
                        new
                        {
                            Id = new Guid("2ffeaf06-7d9a-4c72-8c9d-452ba44a0c6e"),
                            CreateDate = new DateTime(2024, 6, 8, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5917),
                            Grade = 3,
                            ProductId = new Guid("9df7c89c-d1aa-4821-9141-bd0747b422e4"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = new Guid("c622c788-0168-4568-b1af-23c6d244fd37")
                        },
                        new
                        {
                            Id = new Guid("3e58866d-9441-424b-8826-4101047cc65f"),
                            CreateDate = new DateTime(2024, 3, 19, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5921),
                            Grade = 3,
                            ProductId = new Guid("7256b740-9a41-4830-9969-7de9a142c37e"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, ",
                            UserId = new Guid("90a8bb87-3d0a-4f6a-ac22-93e5c5ee5a91")
                        },
                        new
                        {
                            Id = new Guid("474a4356-2fc6-4a30-a197-c9eb0a74930e"),
                            CreateDate = new DateTime(2024, 5, 31, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5926),
                            Grade = 5,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incid",
                            UserId = new Guid("6592d6e8-b6f9-451d-83ac-ee9e9f4af0ea")
                        },
                        new
                        {
                            Id = new Guid("a5640d2e-9ef6-4565-9fda-bea3b474465e"),
                            CreateDate = new DateTime(2024, 4, 9, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5931),
                            Grade = 5,
                            ProductId = new Guid("7d82582d-4bce-4eca-8cd8-0f1431301e00"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt u",
                            UserId = new Guid("ac222c73-4fc7-4ee7-b49a-c12e97419bd6")
                        },
                        new
                        {
                            Id = new Guid("5545ceab-7211-4317-af1f-fbcc8521478e"),
                            CreateDate = new DateTime(2024, 3, 13, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5938),
                            Grade = 3,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adi",
                            UserId = new Guid("5ef9aabf-fc9f-4776-8e51-55a069f0961b")
                        },
                        new
                        {
                            Id = new Guid("22db6c7e-68e7-4c31-a48f-ff267a8660fe"),
                            CreateDate = new DateTime(2024, 5, 27, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5944),
                            Grade = 1,
                            ProductId = new Guid("e017232b-40b2-4f63-85fd-9e0bc16b238f"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = new Guid("c3c516e0-b67d-49ed-9aec-3e7bd9195362")
                        },
                        new
                        {
                            Id = new Guid("f55f270a-5fac-4c61-a268-908d73b710fa"),
                            CreateDate = new DateTime(2024, 3, 20, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5949),
                            Grade = 1,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidid",
                            UserId = new Guid("80aa9164-109a-49ae-b892-991fc24bb281")
                        },
                        new
                        {
                            Id = new Guid("9e56d989-8139-41e3-90d5-711bd07adf5e"),
                            CreateDate = new DateTime(2024, 4, 12, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5954),
                            Grade = 2,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do e",
                            UserId = new Guid("f3b70f98-747c-4884-b07c-e9191c0bdc7f")
                        },
                        new
                        {
                            Id = new Guid("eee94a82-46c9-4cf3-ba4c-75f9049bd4b8"),
                            CreateDate = new DateTime(2024, 5, 15, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5964),
                            Grade = 3,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisi",
                            UserId = new Guid("83458f1d-a8be-419b-936d-f0f906792213")
                        },
                        new
                        {
                            Id = new Guid("3e77085d-dc83-460c-aa39-8fb575bcd497"),
                            CreateDate = new DateTime(2024, 5, 14, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5969),
                            Grade = 4,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing ",
                            UserId = new Guid("609e1360-5965-4965-9d02-4789e9e8f9fc")
                        },
                        new
                        {
                            Id = new Guid("8ae22203-df26-460a-9cff-e318215cc4f2"),
                            CreateDate = new DateTime(2024, 3, 12, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5974),
                            Grade = 2,
                            ProductId = new Guid("89637c57-614c-4403-b5ef-78dfa6b6f5d1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = new Guid("68e17779-80dc-4365-9bca-767696b6e316")
                        },
                        new
                        {
                            Id = new Guid("0c2cdda5-f8ad-4862-a43f-a0a2cf123a23"),
                            CreateDate = new DateTime(2024, 5, 23, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5980),
                            Grade = 4,
                            ProductId = new Guid("89637c57-614c-4403-b5ef-78dfa6b6f5d1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab",
                            UserId = new Guid("d6fa0beb-d8d3-479e-8df1-32565a6f65bb")
                        },
                        new
                        {
                            Id = new Guid("632898b1-d627-403c-ac84-f300b5b279bc"),
                            CreateDate = new DateTime(2024, 4, 14, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5989),
                            Grade = 5,
                            ProductId = new Guid("7256b740-9a41-4830-9969-7de9a142c37e"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididun",
                            UserId = new Guid("e8fb3a21-bb77-49a2-a059-5225b26e5440")
                        },
                        new
                        {
                            Id = new Guid("22fce386-57f1-433e-aacc-12f93b329a5e"),
                            CreateDate = new DateTime(2024, 4, 19, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5994),
                            Grade = 4,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit a",
                            UserId = new Guid("b954828a-d852-4a9c-8750-b9c52ebff9fc")
                        },
                        new
                        {
                            Id = new Guid("cd0b8b71-f64a-4212-8a64-48672c4dd6fa"),
                            CreateDate = new DateTime(2024, 4, 5, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(5999),
                            Grade = 4,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = new Guid("dec65557-3b81-41e6-b8b1-7accb353b3d9")
                        },
                        new
                        {
                            Id = new Guid("9912c67a-9e24-4a83-ab78-2c11a152d81e"),
                            CreateDate = new DateTime(2024, 5, 31, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6060),
                            Grade = 5,
                            ProductId = new Guid("f48175a5-d13a-4780-a281-82936eb6faf3"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = new Guid("1ef47e0e-6a41-47af-8e09-0d01e919ac5f")
                        },
                        new
                        {
                            Id = new Guid("a2a731b1-3ce9-4af5-b7f6-58b684eb85aa"),
                            CreateDate = new DateTime(2024, 3, 10, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6073),
                            Grade = 5,
                            ProductId = new Guid("89637c57-614c-4403-b5ef-78dfa6b6f5d1"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = new Guid("6075bbca-c816-4a7d-8af9-79549b57a9c0")
                        },
                        new
                        {
                            Id = new Guid("b9377aa4-9841-4969-aa93-ca25767607ad"),
                            CreateDate = new DateTime(2024, 3, 23, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6079),
                            Grade = 4,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = new Guid("d907913c-dc0e-4972-b362-b06f768040c3")
                        },
                        new
                        {
                            Id = new Guid("ac785771-56c2-4aff-9d64-261b1c1d2429"),
                            CreateDate = new DateTime(2024, 4, 28, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6083),
                            Grade = 2,
                            ProductId = new Guid("89637c57-614c-4403-b5ef-78dfa6b6f5d1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = new Guid("0eeb6695-e928-4825-b602-b1d99e290f30")
                        },
                        new
                        {
                            Id = new Guid("ca509fbe-eb06-4146-a407-239d2baadfb0"),
                            CreateDate = new DateTime(2024, 4, 13, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6089),
                            Grade = 3,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,",
                            UserId = new Guid("45c6e63e-30a8-4e08-8e3f-9aaa278aa8d0")
                        },
                        new
                        {
                            Id = new Guid("f2214888-f75f-403f-a886-cf6db532073e"),
                            CreateDate = new DateTime(2024, 5, 7, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6097),
                            Grade = 2,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = new Guid("9cb4736c-80f1-41f2-b2ed-b54b5e9b06c4")
                        },
                        new
                        {
                            Id = new Guid("98cedbb7-1a01-4072-9471-c07624c4f674"),
                            CreateDate = new DateTime(2024, 3, 29, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6102),
                            Grade = 1,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor ",
                            UserId = new Guid("adb02eb3-df70-4ac9-8161-163987dcc086")
                        },
                        new
                        {
                            Id = new Guid("c54430c0-644b-4935-b14e-b072f51d5254"),
                            CreateDate = new DateTime(2024, 3, 15, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6108),
                            Grade = 2,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit a",
                            UserId = new Guid("58291b00-33a5-4601-99ea-55fd4c6bcab9")
                        },
                        new
                        {
                            Id = new Guid("f02fbae0-8eaf-487c-a199-b6e818e07230"),
                            CreateDate = new DateTime(2024, 3, 31, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6113),
                            Grade = 2,
                            ProductId = new Guid("89637c57-614c-4403-b5ef-78dfa6b6f5d1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ei",
                            UserId = new Guid("963b7e53-93dd-4200-96a1-c4ab3e1c2d33")
                        },
                        new
                        {
                            Id = new Guid("7d2a8948-1b1a-42aa-853c-d2b44c7ef7f5"),
                            CreateDate = new DateTime(2024, 4, 28, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6122),
                            Grade = 3,
                            ProductId = new Guid("7256b740-9a41-4830-9969-7de9a142c37e"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, se",
                            UserId = new Guid("52a2fdb4-eb70-4790-8a97-4ba17135b899")
                        },
                        new
                        {
                            Id = new Guid("a88bb241-b5e2-4b24-9c8a-8574b58125fb"),
                            CreateDate = new DateTime(2024, 3, 5, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6127),
                            Grade = 3,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = new Guid("9f86c29f-3a76-430a-a4dc-e2eebb56c518")
                        },
                        new
                        {
                            Id = new Guid("12af95db-d3e4-40aa-a9f2-3cfa5793294c"),
                            CreateDate = new DateTime(2024, 5, 26, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6133),
                            Grade = 5,
                            ProductId = new Guid("7d82582d-4bce-4eca-8cd8-0f1431301e00"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = new Guid("df11b5a2-e859-4a18-95b2-26f913950665")
                        },
                        new
                        {
                            Id = new Guid("3823b63d-6003-48bd-8e4c-b339ecf0614d"),
                            CreateDate = new DateTime(2024, 4, 12, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6137),
                            Grade = 2,
                            ProductId = new Guid("7d82582d-4bce-4eca-8cd8-0f1431301e00"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing el",
                            UserId = new Guid("a2f419c5-cd45-4e1a-82fd-7893a2a67a21")
                        },
                        new
                        {
                            Id = new Guid("2ab33316-27fb-4197-bfe0-3e7b804e7c57"),
                            CreateDate = new DateTime(2024, 5, 28, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6148),
                            Grade = 2,
                            ProductId = new Guid("7d82582d-4bce-4eca-8cd8-0f1431301e00"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inc",
                            UserId = new Guid("d0e94e5a-1a96-4872-a509-16716e9faa02")
                        },
                        new
                        {
                            Id = new Guid("248df55e-0e95-4338-a9eb-026a65380c8d"),
                            CreateDate = new DateTime(2024, 4, 11, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6153),
                            Grade = 4,
                            ProductId = new Guid("d8b170fe-c65f-4a12-b38a-3ae020d8a74a"),
                            Status = 2,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = new Guid("c49dd2ba-9096-46de-905b-f7cfbcb6de03")
                        },
                        new
                        {
                            Id = new Guid("6d1119fd-139b-49c7-8e24-1b70de186197"),
                            CreateDate = new DateTime(2024, 4, 16, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6159),
                            Grade = 4,
                            ProductId = new Guid("f48175a5-d13a-4780-a281-82936eb6faf3"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, ",
                            UserId = new Guid("973047f9-c241-414b-8dd0-d9422d3be6e3")
                        },
                        new
                        {
                            Id = new Guid("e0c34ab2-b057-45f1-a0e8-3a6b4a4d9c53"),
                            CreateDate = new DateTime(2024, 5, 29, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6164),
                            Grade = 5,
                            ProductId = new Guid("9df7c89c-d1aa-4821-9141-bd0747b422e4"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididun",
                            UserId = new Guid("f876d177-2e5b-4a76-bc1b-f61173113d14")
                        },
                        new
                        {
                            Id = new Guid("d677ecbd-fb54-4a16-b239-570ca9291bc3"),
                            CreateDate = new DateTime(2024, 5, 9, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6173),
                            Grade = 4,
                            ProductId = new Guid("c9eb75ea-ddd5-4e03-912e-7105135b4df1"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci",
                            UserId = new Guid("fa1bf0fd-2e40-4f08-8701-6b103b310eed")
                        },
                        new
                        {
                            Id = new Guid("78707276-9583-4715-b7a2-ef2061859e03"),
                            CreateDate = new DateTime(2024, 5, 3, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6179),
                            Grade = 3,
                            ProductId = new Guid("f48175a5-d13a-4780-a281-82936eb6faf3"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = new Guid("0fc06da4-b1cd-4445-9ca2-39ff41390203")
                        },
                        new
                        {
                            Id = new Guid("4770a5a7-7fe9-41c3-bfee-57eb7a9e2b42"),
                            CreateDate = new DateTime(2024, 4, 8, 14, 56, 13, 891, DateTimeKind.Local).AddTicks(6184),
                            Grade = 1,
                            ProductId = new Guid("2e8ff855-5ac2-4ff9-ac76-7c868cda9ab3"),
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididun",
                            UserId = new Guid("2ee557d6-0483-4203-ad87-0ca7e6b30919")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
