// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review.Domain;

#nullable disable

namespace Review.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240528155635_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Review.Domain.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 5, 10, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8934),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 3, 6, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8958),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 5, 16, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8974),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 5, 16, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8987),
                            Grade = 2.6000000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 2, 24, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9000),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 3, 18, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9013),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 3, 4, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9026),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 4, 14, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9040),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 4, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9082),
                            Grade = 3.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 4, 15, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9095),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 5, 20, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9112),
                            Grade = 2.6800000000000002,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 3, 22, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9126),
                            Grade = 2.6000000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 3, 28, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9141),
                            Grade = 2.0,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 2, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9153),
                            Grade = 2.6000000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 2, 28, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9169),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 5, 10, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9182),
                            Grade = 2.6000000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 4, 4, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9196),
                            Grade = 2.8799999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 5, 18, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9213),
                            Grade = 2.6800000000000002,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 5, 15, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9226),
                            Grade = 2.8799999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 3, 16, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9241),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2024, 2, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9255),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2024, 3, 30, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9267),
                            Grade = 2.6000000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2024, 2, 26, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9309),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2024, 5, 2, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9322),
                            Grade = 2.6000000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2024, 2, 18, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9337),
                            Grade = 3.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2024, 5, 25, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9350),
                            Grade = 2.8799999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2024, 2, 29, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9364),
                            Grade = 2.0,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2024, 3, 29, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9379),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2024, 2, 28, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9393),
                            Grade = 2.0,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2024, 3, 20, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9407),
                            Grade = 3.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2024, 5, 24, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9421),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2024, 2, 26, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9435),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2024, 3, 25, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9448),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2024, 3, 9, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9462),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2024, 5, 12, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9478),
                            Grade = 2.6800000000000002,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2024, 3, 11, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9491),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2024, 3, 4, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9533),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2024, 5, 26, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9548),
                            Grade = 2.6800000000000002,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2024, 4, 25, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9562),
                            Grade = 2.8799999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2024, 3, 8, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9576),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2024, 3, 20, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9591),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2024, 3, 10, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9604),
                            Grade = 2.6000000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2024, 3, 6, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9617),
                            Grade = 2.0,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(2024, 5, 19, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9633),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 45,
                            CreateDate = new DateTime(2024, 2, 23, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9647),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 46,
                            CreateDate = new DateTime(2024, 3, 8, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9661),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 47,
                            CreateDate = new DateTime(2024, 3, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9675),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 48,
                            CreateDate = new DateTime(2024, 4, 10, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9689),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 49,
                            CreateDate = new DateTime(2024, 4, 12, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9702),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 50,
                            CreateDate = new DateTime(2024, 4, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9715),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 51,
                            CreateDate = new DateTime(2024, 4, 24, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9759),
                            Grade = 3.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 52,
                            CreateDate = new DateTime(2024, 4, 20, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9773),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 53,
                            CreateDate = new DateTime(2024, 4, 27, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9789),
                            Grade = 2.6800000000000002,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 54,
                            CreateDate = new DateTime(2024, 4, 27, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9802),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 55,
                            CreateDate = new DateTime(2024, 2, 19, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9815),
                            Grade = 2.6000000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 56,
                            CreateDate = new DateTime(2024, 3, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9829),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 57,
                            CreateDate = new DateTime(2024, 5, 22, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9843),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 58,
                            CreateDate = new DateTime(2024, 5, 17, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9858),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 59,
                            CreateDate = new DateTime(2024, 5, 25, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9870),
                            Grade = 2.6000000000000001,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 60,
                            CreateDate = new DateTime(2024, 2, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9884),
                            Grade = 2.0,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 61,
                            CreateDate = new DateTime(2024, 4, 6, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9899),
                            Grade = 2.6800000000000002,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 62,
                            CreateDate = new DateTime(2024, 5, 23, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9914),
                            Grade = 2.6800000000000002,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 63,
                            CreateDate = new DateTime(2024, 5, 22, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9958),
                            Grade = 2.6800000000000002,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 64,
                            CreateDate = new DateTime(2024, 2, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9973),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 65,
                            CreateDate = new DateTime(2024, 5, 26, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(9986),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 66,
                            CreateDate = new DateTime(2024, 4, 13, 18, 56, 26, 990, DateTimeKind.Local),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 67,
                            CreateDate = new DateTime(2024, 4, 5, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(14),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 68,
                            CreateDate = new DateTime(2024, 5, 14, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(29),
                            Grade = 2.6800000000000002,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 69,
                            CreateDate = new DateTime(2024, 5, 3, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(44),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 70,
                            CreateDate = new DateTime(2024, 5, 16, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(57),
                            Grade = 3.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 71,
                            CreateDate = new DateTime(2024, 4, 23, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(71),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 72,
                            CreateDate = new DateTime(2024, 5, 6, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(86),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 73,
                            CreateDate = new DateTime(2024, 2, 28, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(99),
                            Grade = 2.8799999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 74,
                            CreateDate = new DateTime(2024, 2, 26, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(113),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 75,
                            CreateDate = new DateTime(2024, 4, 17, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(127),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 76,
                            CreateDate = new DateTime(2024, 2, 23, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(140),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 77,
                            CreateDate = new DateTime(2024, 4, 23, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(180),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 78,
                            CreateDate = new DateTime(2024, 3, 15, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(193),
                            Grade = 2.8799999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 79,
                            CreateDate = new DateTime(2024, 3, 16, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(206),
                            Grade = 2.8799999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 80,
                            CreateDate = new DateTime(2024, 5, 16, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(220),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 81,
                            CreateDate = new DateTime(2024, 3, 28, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(234),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 82,
                            CreateDate = new DateTime(2024, 5, 10, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(247),
                            Grade = 2.8799999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 83,
                            CreateDate = new DateTime(2024, 3, 1, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(261),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 84,
                            CreateDate = new DateTime(2024, 3, 11, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(274),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 85,
                            CreateDate = new DateTime(2024, 4, 26, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(288),
                            Grade = 3.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 86,
                            CreateDate = new DateTime(2024, 5, 1, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(301),
                            Grade = 2.0,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 87,
                            CreateDate = new DateTime(2024, 4, 30, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(315),
                            Grade = 3.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 88,
                            CreateDate = new DateTime(2024, 2, 24, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(328),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 89,
                            CreateDate = new DateTime(2024, 2, 22, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(342),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 90,
                            CreateDate = new DateTime(2024, 5, 7, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(357),
                            Grade = 2.6800000000000002,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 91,
                            CreateDate = new DateTime(2024, 4, 16, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(398),
                            Grade = 2.8799999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 92,
                            CreateDate = new DateTime(2024, 3, 5, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(411),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 93,
                            CreateDate = new DateTime(2024, 5, 21, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(425),
                            Grade = 2.8799999999999999,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 94,
                            CreateDate = new DateTime(2024, 4, 28, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(439),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 95,
                            CreateDate = new DateTime(2024, 3, 17, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(451),
                            Grade = 1.8600000000000001,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 96,
                            CreateDate = new DateTime(2024, 2, 26, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(465),
                            Grade = 2.7999999999999998,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 97,
                            CreateDate = new DateTime(2024, 3, 1, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(479),
                            Grade = 3.3599999999999999,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 98,
                            CreateDate = new DateTime(2024, 4, 8, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(494),
                            Grade = 2.6800000000000002,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 99,
                            CreateDate = new DateTime(2024, 3, 1, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(508),
                            Grade = 2.8199999999999998,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 100,
                            CreateDate = new DateTime(2024, 3, 17, 18, 56, 26, 990, DateTimeKind.Local).AddTicks(522),
                            Grade = 3.0800000000000001,
                            ProductId = 6
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 4, 12, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8614),
                            Grade = 2,
                            ProductId = 7,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 4, 24, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8637),
                            Grade = 5,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo",
                            UserId = 9
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 4, 4, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8639),
                            Grade = 2,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing e",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 4, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8641),
                            Grade = 0,
                            ProductId = 5,
                            RatingId = 13,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu",
                            UserId = 9
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 4, 12, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8643),
                            Grade = 0,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod t",
                            UserId = 6
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 4, 30, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8645),
                            Grade = 3,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing e",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 3, 14, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8646),
                            Grade = 5,
                            ProductId = 5,
                            RatingId = 13,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor",
                            UserId = 8
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 4, 2, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8648),
                            Grade = 4,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 5, 22, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8650),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur ad",
                            UserId = 8
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 3, 11, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8651),
                            Grade = 2,
                            ProductId = 5,
                            RatingId = 13,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ei",
                            UserId = 6
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 4, 28, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8653),
                            Grade = 0,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adi",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 3, 10, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8688),
                            Grade = 5,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt u",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 5, 1, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8690),
                            Grade = 3,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab",
                            UserId = 8
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 5, 7, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8692),
                            Grade = 5,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = 6
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 5, 18, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8694),
                            Grade = 1,
                            ProductId = 5,
                            RatingId = 13,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, ",
                            UserId = 8
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 2, 24, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8696),
                            Grade = 3,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidid",
                            UserId = 8
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 3, 25, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8697),
                            Grade = 3,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt u",
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 2, 23, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8698),
                            Grade = 1,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adip",
                            UserId = 8
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 4, 3, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8700),
                            Grade = 3,
                            ProductId = 5,
                            RatingId = 13,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = 3
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 3, 11, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8701),
                            Grade = 4,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2024, 3, 25, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8703),
                            Grade = 0,
                            ProductId = 1,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed",
                            UserId = 7
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2024, 2, 22, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8704),
                            Grade = 4,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectet",
                            UserId = 5
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2024, 3, 26, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8706),
                            Grade = 0,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adip",
                            UserId = 7
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2024, 4, 18, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8707),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor",
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2024, 2, 22, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8709),
                            Grade = 0,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, se",
                            UserId = 8
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2024, 4, 8, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8710),
                            Grade = 4,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do",
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2024, 3, 29, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8712),
                            Grade = 1,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ",
                            UserId = 7
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2024, 5, 5, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8713),
                            Grade = 5,
                            ProductId = 1,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, ",
                            UserId = 9
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2024, 3, 22, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8715),
                            Grade = 4,
                            ProductId = 9,
                            RatingId = 17,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu",
                            UserId = 8
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2024, 2, 25, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8716),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusm",
                            UserId = 8
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2024, 4, 15, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8717),
                            Grade = 3,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consec",
                            UserId = 5
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2024, 5, 27, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8719),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipi",
                            UserId = 8
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2024, 3, 24, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8720),
                            Grade = 5,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = 5
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2024, 5, 16, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8722),
                            Grade = 5,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicin",
                            UserId = 3
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2024, 3, 11, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8723),
                            Grade = 1,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,",
                            UserId = 6
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2024, 5, 10, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8725),
                            Grade = 3,
                            ProductId = 1,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor",
                            UserId = 9
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2024, 4, 29, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8726),
                            Grade = 3,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2024, 5, 13, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8727),
                            Grade = 4,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicin",
                            UserId = 3
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2024, 5, 9, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8729),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,",
                            UserId = 5
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2024, 3, 26, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8730),
                            Grade = 4,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor",
                            UserId = 5
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2024, 2, 26, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8732),
                            Grade = 5,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ei",
                            UserId = 6
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2024, 4, 29, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8734),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo",
                            UserId = 2
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2024, 5, 20, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8735),
                            Grade = 4,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo",
                            UserId = 1
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(2024, 5, 25, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8736),
                            Grade = 2,
                            ProductId = 7,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adip",
                            UserId = 6
                        },
                        new
                        {
                            Id = 45,
                            CreateDate = new DateTime(2024, 4, 19, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8738),
                            Grade = 3,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidid",
                            UserId = 6
                        },
                        new
                        {
                            Id = 46,
                            CreateDate = new DateTime(2024, 2, 23, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8739),
                            Grade = 5,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo",
                            UserId = 9
                        },
                        new
                        {
                            Id = 47,
                            CreateDate = new DateTime(2024, 4, 5, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8740),
                            Grade = 0,
                            ProductId = 5,
                            RatingId = 13,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipis",
                            UserId = 4
                        },
                        new
                        {
                            Id = 48,
                            CreateDate = new DateTime(2024, 4, 30, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8742),
                            Grade = 5,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu",
                            UserId = 6
                        },
                        new
                        {
                            Id = 49,
                            CreateDate = new DateTime(2024, 5, 20, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8743),
                            Grade = 5,
                            ProductId = 9,
                            RatingId = 17,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = 1
                        },
                        new
                        {
                            Id = 50,
                            CreateDate = new DateTime(2024, 5, 7, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8771),
                            Grade = 4,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing el",
                            UserId = 4
                        },
                        new
                        {
                            Id = 51,
                            CreateDate = new DateTime(2024, 4, 20, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8772),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = 2
                        },
                        new
                        {
                            Id = 52,
                            CreateDate = new DateTime(2024, 3, 20, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8774),
                            Grade = 1,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inc",
                            UserId = 1
                        },
                        new
                        {
                            Id = 53,
                            CreateDate = new DateTime(2024, 2, 28, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8775),
                            Grade = 0,
                            ProductId = 1,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consecte",
                            UserId = 3
                        },
                        new
                        {
                            Id = 54,
                            CreateDate = new DateTime(2024, 5, 15, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8777),
                            Grade = 5,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adi",
                            UserId = 1
                        },
                        new
                        {
                            Id = 55,
                            CreateDate = new DateTime(2024, 3, 9, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8778),
                            Grade = 5,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci",
                            UserId = 2
                        },
                        new
                        {
                            Id = 56,
                            CreateDate = new DateTime(2024, 4, 29, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8780),
                            Grade = 3,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisi",
                            UserId = 9
                        },
                        new
                        {
                            Id = 57,
                            CreateDate = new DateTime(2024, 2, 19, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8781),
                            Grade = 4,
                            ProductId = 9,
                            RatingId = 17,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s",
                            UserId = 3
                        },
                        new
                        {
                            Id = 58,
                            CreateDate = new DateTime(2024, 3, 29, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8782),
                            Grade = 1,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit",
                            UserId = 1
                        },
                        new
                        {
                            Id = 59,
                            CreateDate = new DateTime(2024, 2, 22, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8784),
                            Grade = 2,
                            ProductId = 5,
                            RatingId = 13,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = 7
                        },
                        new
                        {
                            Id = 60,
                            CreateDate = new DateTime(2024, 3, 8, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8786),
                            Grade = 4,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 1
                        },
                        new
                        {
                            Id = 61,
                            CreateDate = new DateTime(2024, 2, 19, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8787),
                            Grade = 2,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ",
                            UserId = 2
                        },
                        new
                        {
                            Id = 62,
                            CreateDate = new DateTime(2024, 3, 12, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8789),
                            Grade = 3,
                            ProductId = 7,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = 1
                        },
                        new
                        {
                            Id = 63,
                            CreateDate = new DateTime(2024, 5, 18, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8790),
                            Grade = 0,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ei",
                            UserId = 7
                        },
                        new
                        {
                            Id = 64,
                            CreateDate = new DateTime(2024, 2, 23, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8792),
                            Grade = 5,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consecte",
                            UserId = 7
                        },
                        new
                        {
                            Id = 65,
                            CreateDate = new DateTime(2024, 3, 20, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8793),
                            Grade = 0,
                            ProductId = 1,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci",
                            UserId = 2
                        },
                        new
                        {
                            Id = 66,
                            CreateDate = new DateTime(2024, 5, 17, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8794),
                            Grade = 0,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ",
                            UserId = 9
                        },
                        new
                        {
                            Id = 67,
                            CreateDate = new DateTime(2024, 3, 8, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8796),
                            Grade = 0,
                            ProductId = 9,
                            RatingId = 17,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed ",
                            UserId = 8
                        },
                        new
                        {
                            Id = 68,
                            CreateDate = new DateTime(2024, 5, 12, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8797),
                            Grade = 4,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor",
                            UserId = 9
                        },
                        new
                        {
                            Id = 69,
                            CreateDate = new DateTime(2024, 3, 10, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8798),
                            Grade = 1,
                            ProductId = 9,
                            RatingId = 17,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisi",
                            UserId = 4
                        },
                        new
                        {
                            Id = 70,
                            CreateDate = new DateTime(2024, 4, 2, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8800),
                            Grade = 4,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = 5
                        },
                        new
                        {
                            Id = 71,
                            CreateDate = new DateTime(2024, 4, 6, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8801),
                            Grade = 5,
                            ProductId = 9,
                            RatingId = 17,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = 3
                        },
                        new
                        {
                            Id = 72,
                            CreateDate = new DateTime(2024, 2, 18, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8803),
                            Grade = 1,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur ",
                            UserId = 9
                        },
                        new
                        {
                            Id = 73,
                            CreateDate = new DateTime(2024, 3, 30, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8804),
                            Grade = 1,
                            ProductId = 1,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidid",
                            UserId = 5
                        },
                        new
                        {
                            Id = 74,
                            CreateDate = new DateTime(2024, 3, 7, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8805),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, cons",
                            UserId = 2
                        },
                        new
                        {
                            Id = 75,
                            CreateDate = new DateTime(2024, 3, 16, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8807),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = 9
                        },
                        new
                        {
                            Id = 76,
                            CreateDate = new DateTime(2024, 5, 10, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8808),
                            Grade = 4,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab",
                            UserId = 5
                        },
                        new
                        {
                            Id = 77,
                            CreateDate = new DateTime(2024, 5, 8, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8810),
                            Grade = 5,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectet",
                            UserId = 6
                        },
                        new
                        {
                            Id = 78,
                            CreateDate = new DateTime(2024, 3, 18, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8812),
                            Grade = 2,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ",
                            UserId = 9
                        },
                        new
                        {
                            Id = 79,
                            CreateDate = new DateTime(2024, 2, 24, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8813),
                            Grade = 3,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = 1
                        },
                        new
                        {
                            Id = 80,
                            CreateDate = new DateTime(2024, 3, 23, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8814),
                            Grade = 4,
                            ProductId = 9,
                            RatingId = 17,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu",
                            UserId = 5
                        },
                        new
                        {
                            Id = 81,
                            CreateDate = new DateTime(2024, 5, 26, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8816),
                            Grade = 0,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci",
                            UserId = 4
                        },
                        new
                        {
                            Id = 82,
                            CreateDate = new DateTime(2024, 3, 8, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8817),
                            Grade = 0,
                            ProductId = 9,
                            RatingId = 17,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt u",
                            UserId = 5
                        },
                        new
                        {
                            Id = 83,
                            CreateDate = new DateTime(2024, 4, 13, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8818),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 1
                        },
                        new
                        {
                            Id = 84,
                            CreateDate = new DateTime(2024, 2, 24, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8820),
                            Grade = 4,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi",
                            UserId = 2
                        },
                        new
                        {
                            Id = 85,
                            CreateDate = new DateTime(2024, 3, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8821),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisi",
                            UserId = 4
                        },
                        new
                        {
                            Id = 86,
                            CreateDate = new DateTime(2024, 4, 22, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8823),
                            Grade = 5,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, se",
                            UserId = 2
                        },
                        new
                        {
                            Id = 87,
                            CreateDate = new DateTime(2024, 4, 6, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8824),
                            Grade = 3,
                            ProductId = 2,
                            RatingId = 28,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius",
                            UserId = 9
                        },
                        new
                        {
                            Id = 88,
                            CreateDate = new DateTime(2024, 4, 25, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8826),
                            Grade = 2,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 2
                        },
                        new
                        {
                            Id = 89,
                            CreateDate = new DateTime(2024, 4, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8873),
                            Grade = 2,
                            ProductId = 7,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing e",
                            UserId = 1
                        },
                        new
                        {
                            Id = 90,
                            CreateDate = new DateTime(2024, 2, 25, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8875),
                            Grade = 2,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inc",
                            UserId = 7
                        },
                        new
                        {
                            Id = 91,
                            CreateDate = new DateTime(2024, 4, 10, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8876),
                            Grade = 1,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 6
                        },
                        new
                        {
                            Id = 92,
                            CreateDate = new DateTime(2024, 4, 13, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8877),
                            Grade = 3,
                            ProductId = 5,
                            RatingId = 13,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit",
                            UserId = 6
                        },
                        new
                        {
                            Id = 93,
                            CreateDate = new DateTime(2024, 4, 14, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8879),
                            Grade = 2,
                            ProductId = 5,
                            RatingId = 13,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius",
                            UserId = 1
                        },
                        new
                        {
                            Id = 94,
                            CreateDate = new DateTime(2024, 3, 23, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8881),
                            Grade = 5,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo",
                            UserId = 7
                        },
                        new
                        {
                            Id = 95,
                            CreateDate = new DateTime(2024, 3, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8882),
                            Grade = 3,
                            ProductId = 4,
                            RatingId = 15,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut",
                            UserId = 7
                        },
                        new
                        {
                            Id = 96,
                            CreateDate = new DateTime(2024, 5, 21, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8883),
                            Grade = 0,
                            ProductId = 8,
                            RatingId = 11,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 97,
                            CreateDate = new DateTime(2024, 5, 11, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8885),
                            Grade = 0,
                            ProductId = 3,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur a",
                            UserId = 1
                        },
                        new
                        {
                            Id = 98,
                            CreateDate = new DateTime(2024, 2, 29, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8886),
                            Grade = 4,
                            ProductId = 1,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur ad",
                            UserId = 6
                        },
                        new
                        {
                            Id = 99,
                            CreateDate = new DateTime(2024, 5, 6, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8887),
                            Grade = 0,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor ",
                            UserId = 7
                        },
                        new
                        {
                            Id = 100,
                            CreateDate = new DateTime(2024, 3, 18, 18, 56, 26, 989, DateTimeKind.Local).AddTicks(8889),
                            Grade = 4,
                            ProductId = 7,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Review", b =>
                {
                    b.HasOne("Review.Domain.Models.Rating", "Rating")
                        .WithMany("Reviews")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Review.Domain.Models.Rating", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
