// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review.Domain;

#nullable disable

namespace Review.Domain.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240528144327_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Review.Domain.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 4, 29, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8782),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 3, 27, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8803),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 19, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8821),
                            Grade = 2.7999999999999998,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 4, 29, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8836),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 3, 9, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8852),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 5, 8, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8895),
                            Grade = 3.0800000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 4, 12, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8911),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 3, 10, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8926),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 5, 27, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8940),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 3, 25, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8955),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 3, 17, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8969),
                            Grade = 1.71,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 2, 20, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8985),
                            Grade = 3.1800000000000002,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 3, 21, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9001),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 5, 13, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9015),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 4, 14, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9030),
                            Grade = 3.1800000000000002,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 4, 20, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9043),
                            Grade = 1.71,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 5, 20, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9058),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 5, 24, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9072),
                            Grade = 2.8799999999999999,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 3, 1, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9085),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 2, 19, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9099),
                            Grade = 2.8799999999999999,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2024, 4, 22, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9168),
                            Grade = 3.0800000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2024, 4, 17, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9183),
                            Grade = 2.8799999999999999,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2024, 5, 1, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9199),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2024, 4, 25, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9212),
                            Grade = 1.71,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2024, 3, 7, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9226),
                            Grade = 2.8799999999999999,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2024, 3, 29, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9240),
                            Grade = 1.71,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2024, 3, 30, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9253),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2024, 5, 25, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9269),
                            Grade = 2.7999999999999998,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2024, 2, 20, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9283),
                            Grade = 1.71,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2024, 5, 9, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9298),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2024, 5, 11, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9311),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2024, 3, 15, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9326),
                            Grade = 2.7999999999999998,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2024, 5, 16, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9341),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2024, 5, 6, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9357),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2024, 4, 9, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9372),
                            Grade = 3.0800000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2024, 4, 24, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9385),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2024, 3, 15, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9429),
                            Grade = 3.0800000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2024, 5, 5, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9443),
                            Grade = 1.71,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2024, 5, 13, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9458),
                            Grade = 3.1800000000000002,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2024, 5, 24, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9473),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2024, 3, 20, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9488),
                            Grade = 3.0800000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2024, 4, 16, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9502),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2024, 5, 21, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9517),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(2024, 5, 9, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9532),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 45,
                            CreateDate = new DateTime(2024, 4, 22, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9545),
                            Grade = 2.8799999999999999,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 46,
                            CreateDate = new DateTime(2024, 5, 1, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9560),
                            Grade = 2.7999999999999998,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 47,
                            CreateDate = new DateTime(2024, 5, 14, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9575),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 48,
                            CreateDate = new DateTime(2024, 3, 4, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9590),
                            Grade = 2.7999999999999998,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 49,
                            CreateDate = new DateTime(2024, 4, 22, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9605),
                            Grade = 3.0800000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 50,
                            CreateDate = new DateTime(2024, 3, 27, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9618),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 51,
                            CreateDate = new DateTime(2024, 5, 26, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9669),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 52,
                            CreateDate = new DateTime(2024, 5, 5, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9684),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 53,
                            CreateDate = new DateTime(2024, 3, 22, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9699),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 54,
                            CreateDate = new DateTime(2024, 4, 18, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9713),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 55,
                            CreateDate = new DateTime(2024, 3, 4, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9728),
                            Grade = 3.1800000000000002,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 56,
                            CreateDate = new DateTime(2024, 2, 29, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9743),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 57,
                            CreateDate = new DateTime(2024, 4, 3, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9758),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 58,
                            CreateDate = new DateTime(2024, 4, 11, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9772),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 59,
                            CreateDate = new DateTime(2024, 3, 2, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9787),
                            Grade = 3.0800000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 60,
                            CreateDate = new DateTime(2024, 4, 14, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9802),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 61,
                            CreateDate = new DateTime(2024, 4, 25, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9817),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 62,
                            CreateDate = new DateTime(2024, 3, 20, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9832),
                            Grade = 2.7999999999999998,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 63,
                            CreateDate = new DateTime(2024, 3, 12, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9847),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 64,
                            CreateDate = new DateTime(2024, 4, 9, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9862),
                            Grade = 3.0800000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 65,
                            CreateDate = new DateTime(2024, 5, 2, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9904),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 66,
                            CreateDate = new DateTime(2024, 5, 24, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9919),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 67,
                            CreateDate = new DateTime(2024, 5, 8, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9932),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 68,
                            CreateDate = new DateTime(2024, 4, 17, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9947),
                            Grade = 2.7999999999999998,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 69,
                            CreateDate = new DateTime(2024, 4, 24, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9962),
                            Grade = 3.0800000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 70,
                            CreateDate = new DateTime(2024, 3, 29, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9977),
                            Grade = 3.0800000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 71,
                            CreateDate = new DateTime(2024, 4, 30, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(9991),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 72,
                            CreateDate = new DateTime(2024, 2, 27, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(5),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 73,
                            CreateDate = new DateTime(2024, 3, 24, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(19),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 74,
                            CreateDate = new DateTime(2024, 5, 14, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(34),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 75,
                            CreateDate = new DateTime(2024, 3, 14, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(47),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 76,
                            CreateDate = new DateTime(2024, 3, 25, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(61),
                            Grade = 2.8799999999999999,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 77,
                            CreateDate = new DateTime(2024, 2, 29, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(75),
                            Grade = 2.8799999999999999,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 78,
                            CreateDate = new DateTime(2024, 4, 26, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(89),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 79,
                            CreateDate = new DateTime(2024, 3, 26, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(104),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 80,
                            CreateDate = new DateTime(2024, 2, 25, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(144),
                            Grade = 2.1200000000000001,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 81,
                            CreateDate = new DateTime(2024, 3, 13, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(158),
                            Grade = 1.71,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 82,
                            CreateDate = new DateTime(2024, 4, 18, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(173),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 83,
                            CreateDate = new DateTime(2024, 3, 17, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(187),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 84,
                            CreateDate = new DateTime(2024, 4, 15, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(202),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 85,
                            CreateDate = new DateTime(2024, 5, 23, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(217),
                            Grade = 3.0800000000000001,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 86,
                            CreateDate = new DateTime(2024, 3, 3, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(230),
                            Grade = 1.71,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 87,
                            CreateDate = new DateTime(2024, 4, 16, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(246),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 88,
                            CreateDate = new DateTime(2024, 3, 26, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(260),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 89,
                            CreateDate = new DateTime(2024, 4, 24, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(274),
                            Grade = 2.8799999999999999,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 90,
                            CreateDate = new DateTime(2024, 5, 17, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(287),
                            Grade = 2.8799999999999999,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 91,
                            CreateDate = new DateTime(2024, 3, 31, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(302),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 92,
                            CreateDate = new DateTime(2024, 5, 14, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(316),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 93,
                            CreateDate = new DateTime(2024, 5, 9, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(332),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 94,
                            CreateDate = new DateTime(2024, 3, 25, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(383),
                            Grade = 2.7999999999999998,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 95,
                            CreateDate = new DateTime(2024, 5, 15, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(398),
                            Grade = 1.6399999999999999,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 96,
                            CreateDate = new DateTime(2024, 3, 26, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(413),
                            Grade = 2.0699999999999998,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 97,
                            CreateDate = new DateTime(2024, 2, 24, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(427),
                            Grade = 1.71,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 98,
                            CreateDate = new DateTime(2024, 5, 14, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(440),
                            Grade = 1.71,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 99,
                            CreateDate = new DateTime(2024, 4, 27, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(455),
                            Grade = 2.0800000000000001,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 100,
                            CreateDate = new DateTime(2024, 4, 6, 17, 43, 17, 924, DateTimeKind.Local).AddTicks(470),
                            Grade = 2.7999999999999998,
                            ProductId = 7
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 5, 18, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8358),
                            Grade = 2,
                            ProductId = 9,
                            RatingId = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 5, 19, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8375),
                            Grade = 5,
                            ProductId = 5,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 4, 19, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8377),
                            Grade = 0,
                            ProductId = 1,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 4, 15, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8440),
                            Grade = 2,
                            ProductId = 2,
                            RatingId = 5,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisic",
                            UserId = 9
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 4, 8, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8442),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor i",
                            UserId = 6
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 3, 21, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8444),
                            Grade = 0,
                            ProductId = 2,
                            RatingId = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adi",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2024, 2, 19, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8446),
                            Grade = 4,
                            ProductId = 8,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2024, 5, 5, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8448),
                            Grade = 4,
                            ProductId = 9,
                            RatingId = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiu",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2024, 4, 3, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8449),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur ",
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2024, 2, 25, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8451),
                            Grade = 0,
                            ProductId = 9,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut",
                            UserId = 6
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2024, 5, 16, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8452),
                            Grade = 1,
                            ProductId = 6,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit ",
                            UserId = 6
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2024, 2, 24, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8454),
                            Grade = 1,
                            ProductId = 9,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit ame",
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2024, 3, 29, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8456),
                            Grade = 4,
                            ProductId = 7,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2024, 5, 6, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8457),
                            Grade = 2,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2024, 5, 7, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8459),
                            Grade = 5,
                            ProductId = 2,
                            RatingId = 5,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = 8
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2024, 4, 5, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8460),
                            Grade = 3,
                            ProductId = 6,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2024, 4, 7, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8462),
                            Grade = 5,
                            ProductId = 2,
                            RatingId = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2024, 3, 21, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8464),
                            Grade = 2,
                            ProductId = 5,
                            RatingId = 5,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consect",
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2024, 3, 8, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8465),
                            Grade = 1,
                            ProductId = 7,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing ",
                            UserId = 7
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2024, 4, 3, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8466),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab",
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2024, 5, 24, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8468),
                            Grade = 1,
                            ProductId = 6,
                            RatingId = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = 9
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2024, 5, 27, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8469),
                            Grade = 2,
                            ProductId = 1,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, ",
                            UserId = 6
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2024, 3, 12, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8471),
                            Grade = 0,
                            ProductId = 6,
                            RatingId = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, con",
                            UserId = 2
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2024, 5, 23, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8473),
                            Grade = 1,
                            ProductId = 2,
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab",
                            UserId = 7
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2024, 2, 26, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8474),
                            Grade = 2,
                            ProductId = 3,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiu",
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2024, 5, 14, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8476),
                            Grade = 0,
                            ProductId = 4,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit a",
                            UserId = 6
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2024, 4, 10, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8478),
                            Grade = 1,
                            ProductId = 5,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit a",
                            UserId = 6
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2024, 5, 9, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8479),
                            Grade = 3,
                            ProductId = 6,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = 7
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2024, 3, 4, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8481),
                            Grade = 0,
                            ProductId = 9,
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo",
                            UserId = 6
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2024, 5, 10, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8483),
                            Grade = 2,
                            ProductId = 9,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = 5
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2024, 3, 3, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8484),
                            Grade = 0,
                            ProductId = 1,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet,",
                            UserId = 4
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2024, 2, 28, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8486),
                            Grade = 0,
                            ProductId = 5,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = 5
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2024, 5, 6, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8487),
                            Grade = 0,
                            ProductId = 9,
                            RatingId = 3,
                            Status = 0,
                            Text = "Lorem ipsum dolor si",
                            UserId = 5
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2024, 3, 5, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8489),
                            Grade = 0,
                            ProductId = 8,
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur ",
                            UserId = 7
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2024, 4, 24, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8490),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 5,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = 8
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2024, 3, 12, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8492),
                            Grade = 0,
                            ProductId = 8,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = 5
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2024, 3, 11, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8493),
                            Grade = 3,
                            ProductId = 6,
                            RatingId = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, se",
                            UserId = 9
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2024, 3, 28, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8495),
                            Grade = 1,
                            ProductId = 3,
                            RatingId = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = 6
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2024, 3, 2, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8496),
                            Grade = 3,
                            ProductId = 9,
                            RatingId = 3,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididu",
                            UserId = 6
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2024, 3, 7, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8498),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor",
                            UserId = 4
                        },
                        new
                        {
                            Id = 41,
                            CreateDate = new DateTime(2024, 4, 10, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8499),
                            Grade = 5,
                            ProductId = 2,
                            RatingId = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labor",
                            UserId = 5
                        },
                        new
                        {
                            Id = 42,
                            CreateDate = new DateTime(2024, 3, 22, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8500),
                            Grade = 2,
                            ProductId = 8,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consect",
                            UserId = 8
                        },
                        new
                        {
                            Id = 43,
                            CreateDate = new DateTime(2024, 3, 26, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8502),
                            Grade = 2,
                            ProductId = 1,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, co",
                            UserId = 5
                        },
                        new
                        {
                            Id = 44,
                            CreateDate = new DateTime(2024, 3, 5, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8504),
                            Grade = 4,
                            ProductId = 8,
                            RatingId = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet",
                            UserId = 3
                        },
                        new
                        {
                            Id = 45,
                            CreateDate = new DateTime(2024, 5, 26, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8587),
                            Grade = 1,
                            ProductId = 4,
                            RatingId = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing e",
                            UserId = 5
                        },
                        new
                        {
                            Id = 46,
                            CreateDate = new DateTime(2024, 3, 20, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8589),
                            Grade = 3,
                            ProductId = 1,
                            RatingId = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consecte",
                            UserId = 5
                        },
                        new
                        {
                            Id = 47,
                            CreateDate = new DateTime(2024, 3, 12, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8591),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 5,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit a",
                            UserId = 1
                        },
                        new
                        {
                            Id = 48,
                            CreateDate = new DateTime(2024, 5, 22, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8592),
                            Grade = 2,
                            ProductId = 7,
                            RatingId = 5,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisi",
                            UserId = 8
                        },
                        new
                        {
                            Id = 49,
                            CreateDate = new DateTime(2024, 5, 26, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8594),
                            Grade = 1,
                            ProductId = 5,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab",
                            UserId = 5
                        },
                        new
                        {
                            Id = 50,
                            CreateDate = new DateTime(2024, 3, 4, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8595),
                            Grade = 5,
                            ProductId = 4,
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed d",
                            UserId = 5
                        },
                        new
                        {
                            Id = 51,
                            CreateDate = new DateTime(2024, 5, 11, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8596),
                            Grade = 4,
                            ProductId = 5,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, se",
                            UserId = 8
                        },
                        new
                        {
                            Id = 52,
                            CreateDate = new DateTime(2024, 5, 4, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8598),
                            Grade = 3,
                            ProductId = 7,
                            RatingId = 3,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inc",
                            UserId = 7
                        },
                        new
                        {
                            Id = 53,
                            CreateDate = new DateTime(2024, 4, 4, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8599),
                            Grade = 5,
                            ProductId = 3,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = 1
                        },
                        new
                        {
                            Id = 54,
                            CreateDate = new DateTime(2024, 5, 25, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8601),
                            Grade = 1,
                            ProductId = 4,
                            RatingId = 5,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo",
                            UserId = 3
                        },
                        new
                        {
                            Id = 55,
                            CreateDate = new DateTime(2024, 5, 2, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8602),
                            Grade = 4,
                            ProductId = 1,
                            RatingId = 5,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ",
                            UserId = 5
                        },
                        new
                        {
                            Id = 56,
                            CreateDate = new DateTime(2024, 3, 21, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8604),
                            Grade = 5,
                            ProductId = 7,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 57,
                            CreateDate = new DateTime(2024, 5, 27, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8605),
                            Grade = 2,
                            ProductId = 4,
                            RatingId = 6,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,",
                            UserId = 1
                        },
                        new
                        {
                            Id = 58,
                            CreateDate = new DateTime(2024, 5, 18, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8607),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = 1
                        },
                        new
                        {
                            Id = 59,
                            CreateDate = new DateTime(2024, 4, 12, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8608),
                            Grade = 4,
                            ProductId = 9,
                            RatingId = 5,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut",
                            UserId = 1
                        },
                        new
                        {
                            Id = 60,
                            CreateDate = new DateTime(2024, 4, 8, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8609),
                            Grade = 0,
                            ProductId = 3,
                            RatingId = 5,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing ",
                            UserId = 5
                        },
                        new
                        {
                            Id = 61,
                            CreateDate = new DateTime(2024, 3, 7, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8611),
                            Grade = 0,
                            ProductId = 1,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = 3
                        },
                        new
                        {
                            Id = 62,
                            CreateDate = new DateTime(2024, 5, 3, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8612),
                            Grade = 3,
                            ProductId = 5,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur",
                            UserId = 3
                        },
                        new
                        {
                            Id = 63,
                            CreateDate = new DateTime(2024, 4, 17, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8614),
                            Grade = 3,
                            ProductId = 7,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod te",
                            UserId = 5
                        },
                        new
                        {
                            Id = 64,
                            CreateDate = new DateTime(2024, 2, 27, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8615),
                            Grade = 2,
                            ProductId = 9,
                            RatingId = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incidi",
                            UserId = 1
                        },
                        new
                        {
                            Id = 65,
                            CreateDate = new DateTime(2024, 4, 5, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8617),
                            Grade = 3,
                            ProductId = 7,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipi",
                            UserId = 2
                        },
                        new
                        {
                            Id = 66,
                            CreateDate = new DateTime(2024, 5, 23, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8618),
                            Grade = 4,
                            ProductId = 8,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adi",
                            UserId = 5
                        },
                        new
                        {
                            Id = 67,
                            CreateDate = new DateTime(2024, 4, 21, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8619),
                            Grade = 1,
                            ProductId = 9,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectet",
                            UserId = 5
                        },
                        new
                        {
                            Id = 68,
                            CreateDate = new DateTime(2024, 5, 3, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8621),
                            Grade = 1,
                            ProductId = 7,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adi",
                            UserId = 4
                        },
                        new
                        {
                            Id = 69,
                            CreateDate = new DateTime(2024, 2, 18, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8623),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = 4
                        },
                        new
                        {
                            Id = 70,
                            CreateDate = new DateTime(2024, 4, 2, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8624),
                            Grade = 2,
                            ProductId = 2,
                            RatingId = 5,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do",
                            UserId = 8
                        },
                        new
                        {
                            Id = 71,
                            CreateDate = new DateTime(2024, 4, 10, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8625),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut lab",
                            UserId = 2
                        },
                        new
                        {
                            Id = 72,
                            CreateDate = new DateTime(2024, 5, 21, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8627),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = 6
                        },
                        new
                        {
                            Id = 73,
                            CreateDate = new DateTime(2024, 5, 10, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8628),
                            Grade = 2,
                            ProductId = 1,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing ",
                            UserId = 9
                        },
                        new
                        {
                            Id = 74,
                            CreateDate = new DateTime(2024, 4, 4, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8630),
                            Grade = 1,
                            ProductId = 9,
                            RatingId = 9,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 75,
                            CreateDate = new DateTime(2024, 5, 25, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8631),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius",
                            UserId = 3
                        },
                        new
                        {
                            Id = 76,
                            CreateDate = new DateTime(2024, 3, 20, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8632),
                            Grade = 5,
                            ProductId = 9,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do e",
                            UserId = 8
                        },
                        new
                        {
                            Id = 77,
                            CreateDate = new DateTime(2024, 2, 26, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8634),
                            Grade = 3,
                            ProductId = 2,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur ad",
                            UserId = 8
                        },
                        new
                        {
                            Id = 78,
                            CreateDate = new DateTime(2024, 4, 28, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8635),
                            Grade = 2,
                            ProductId = 1,
                            RatingId = 7,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor ",
                            UserId = 7
                        },
                        new
                        {
                            Id = 79,
                            CreateDate = new DateTime(2024, 3, 12, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8637),
                            Grade = 5,
                            ProductId = 9,
                            RatingId = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiu",
                            UserId = 4
                        },
                        new
                        {
                            Id = 80,
                            CreateDate = new DateTime(2024, 3, 31, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8638),
                            Grade = 2,
                            ProductId = 7,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consect",
                            UserId = 5
                        },
                        new
                        {
                            Id = 81,
                            CreateDate = new DateTime(2024, 3, 10, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8639),
                            Grade = 4,
                            ProductId = 8,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut",
                            UserId = 1
                        },
                        new
                        {
                            Id = 82,
                            CreateDate = new DateTime(2024, 4, 26, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8640),
                            Grade = 5,
                            ProductId = 8,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur ",
                            UserId = 6
                        },
                        new
                        {
                            Id = 83,
                            CreateDate = new DateTime(2024, 4, 22, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8690),
                            Grade = 3,
                            ProductId = 3,
                            RatingId = 3,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tem",
                            UserId = 3
                        },
                        new
                        {
                            Id = 84,
                            CreateDate = new DateTime(2024, 3, 28, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8692),
                            Grade = 4,
                            ProductId = 7,
                            RatingId = 1,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incid",
                            UserId = 1
                        },
                        new
                        {
                            Id = 85,
                            CreateDate = new DateTime(2024, 2, 20, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8693),
                            Grade = 1,
                            ProductId = 7,
                            RatingId = 3,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing e",
                            UserId = 7
                        },
                        new
                        {
                            Id = 86,
                            CreateDate = new DateTime(2024, 5, 14, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8695),
                            Grade = 5,
                            ProductId = 6,
                            RatingId = 4,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ",
                            UserId = 5
                        },
                        new
                        {
                            Id = 87,
                            CreateDate = new DateTime(2024, 3, 31, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8696),
                            Grade = 0,
                            ProductId = 1,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in",
                            UserId = 7
                        },
                        new
                        {
                            Id = 88,
                            CreateDate = new DateTime(2024, 4, 15, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8698),
                            Grade = 5,
                            ProductId = 8,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing ",
                            UserId = 5
                        },
                        new
                        {
                            Id = 89,
                            CreateDate = new DateTime(2024, 5, 24, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8699),
                            Grade = 2,
                            ProductId = 7,
                            RatingId = 8,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod",
                            UserId = 1
                        },
                        new
                        {
                            Id = 90,
                            CreateDate = new DateTime(2024, 3, 1, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8701),
                            Grade = 1,
                            ProductId = 5,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la",
                            UserId = 8
                        },
                        new
                        {
                            Id = 91,
                            CreateDate = new DateTime(2024, 3, 13, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8703),
                            Grade = 4,
                            ProductId = 7,
                            RatingId = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit am",
                            UserId = 8
                        },
                        new
                        {
                            Id = 92,
                            CreateDate = new DateTime(2024, 5, 10, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8704),
                            Grade = 3,
                            ProductId = 8,
                            RatingId = 4,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp",
                            UserId = 3
                        },
                        new
                        {
                            Id = 93,
                            CreateDate = new DateTime(2024, 4, 17, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8705),
                            Grade = 3,
                            ProductId = 1,
                            RatingId = 8,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor ",
                            UserId = 1
                        },
                        new
                        {
                            Id = 94,
                            CreateDate = new DateTime(2024, 5, 7, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8707),
                            Grade = 1,
                            ProductId = 6,
                            RatingId = 9,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = 8
                        },
                        new
                        {
                            Id = 95,
                            CreateDate = new DateTime(2024, 4, 17, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8708),
                            Grade = 3,
                            ProductId = 7,
                            RatingId = 2,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit,",
                            UserId = 1
                        },
                        new
                        {
                            Id = 96,
                            CreateDate = new DateTime(2024, 3, 15, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8710),
                            Grade = 1,
                            ProductId = 9,
                            RatingId = 7,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod t",
                            UserId = 5
                        },
                        new
                        {
                            Id = 97,
                            CreateDate = new DateTime(2024, 4, 10, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8711),
                            Grade = 2,
                            ProductId = 6,
                            RatingId = 1,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
                            UserId = 5
                        },
                        new
                        {
                            Id = 98,
                            CreateDate = new DateTime(2024, 5, 2, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8712),
                            Grade = 4,
                            ProductId = 3,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing el",
                            UserId = 1
                        },
                        new
                        {
                            Id = 99,
                            CreateDate = new DateTime(2024, 3, 30, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8714),
                            Grade = 1,
                            ProductId = 4,
                            RatingId = 2,
                            Status = 1,
                            Text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod ",
                            UserId = 4
                        },
                        new
                        {
                            Id = 100,
                            CreateDate = new DateTime(2024, 4, 22, 17, 43, 17, 923, DateTimeKind.Local).AddTicks(8715),
                            Grade = 4,
                            ProductId = 7,
                            RatingId = 6,
                            Status = 0,
                            Text = "Lorem ipsum dolor sit amet, consectetu",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Review.Domain.Models.Review", b =>
                {
                    b.HasOne("Review.Domain.Models.Rating", "Rating")
                        .WithMany("Reviews")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Review.Domain.Models.Rating", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
